import{useEffect,useMemo,useRef,useState}from'react';import{useParams}from'react-router-dom';import styled from'styled-components';import{ArrowLeft,ArrowRight,Check,Cloud,CloudOff,Leaf}from'lucide-react';import{api}from'../api';import type{Question,Survey}from'../types';import{Button,Card,Page,Shell}from'../ui';
const Header=styled.header`padding:24px 0 10px;display:flex;align-items:center;gap:10px;color:#526f5b;font-weight:750;letter-spacing:.02em`;
const Welcome=styled(Card)`margin:8vh auto 0;padding:clamp(28px,7vw,56px);h1{font:500 clamp(34px,7vw,54px)/1.08 Georgia,serif;margin:18px 0;color:#2f4938}p{font-size:17px;line-height:1.65;color:#5d6b61;white-space:pre-line}.meta{display:flex;gap:18px;color:#728077;font-size:14px;margin:26px 0;flex-wrap:wrap}`;
const Top=styled.div`position:sticky;top:0;padding:14px 0;background:rgba(243,246,240,.9);backdrop-filter:blur(12px);z-index:2`;
const Bar=styled.div`height:5px;background:#dfe7dc;border-radius:9px;overflow:hidden;i{display:block;height:100%;background:#6e8e76;transition:width .35s}`;
const QuestionCard=styled(Card)`margin:5vh auto 24px;padding:clamp(24px,6vw,48px);min-height:440px;display:flex;flex-direction:column;.eyebrow{color:#738278;font-size:13px}.question{font:500 clamp(25px,5vw,36px)/1.25 Georgia,serif;color:#293c30;margin:18px 0 28px}`;
const Options=styled.div`display:grid;gap:10px;margin:auto 0;`;
const Choice=styled.button<{$active:boolean}>`text-align:left;display:flex;align-items:center;gap:13px;width:100%;padding:15px 16px;border-radius:16px;border:1px solid ${p=>p.$active?'#78977f':'#dbe3da'};background:${p=>p.$active?'#e5eee3':'#fff'};color:#304036;min-height:54px;transition:.15s;.dot{width:22px;height:22px;border-radius:50%;border:1px solid #9bab9e;display:grid;place-items:center;flex:none;background:${p=>p.$active?'#65836d':'transparent'};color:white}`;
const Input=styled.input`width:100%;border:0;border-bottom:2px solid #b8c7ba;background:transparent;padding:14px 4px;font-size:20px;color:#293c30;outline:none;&:focus{border-color:#607f68}`;
const Nav=styled.div`display:flex;align-items:center;justify-content:space-between;margin-top:30px;gap:10px;.save{font-size:12px;color:#7a887f;display:flex;align-items:center;gap:5px}`;
type Value=string|number|string[];
export function SurveyPage(){const{slug='anketa'}=useParams();const[survey,setSurvey]=useState<Survey>();const[started,setStarted]=useState(false);const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<Record<string,Value>>({});const[token,setToken]=useState('');const[saving,setSaving]=useState(false);const[offline,setOffline]=useState(false);const[done,setDone]=useState(false);const timer=useRef<number|undefined>(undefined);
useEffect(()=>{api.get(`/public/surveys/${slug}`).then(r=>setSurvey(r.data))},[slug]);
async function start(){const key=`survey_session_${slug}`;let t=localStorage.getItem(key);if(!t){const r=await api.post(`/public/surveys/${slug}/sessions`);t=r.data.token;localStorage.setItem(key,t!)}else{try{const r=await api.get(`/public/sessions/${t}`);if(r.data.status==='completed'){localStorage.removeItem(key);return start()}setIndex(Math.min(r.data.currentPosition??0,survey!.questions.length-1));setAnswers(Object.fromEntries(r.data.answers.map((a:{questionId:string;value:Value})=>[a.questionId,a.value])))}catch{localStorage.removeItem(key);return start()}}setToken(t!);setStarted(true)}
async function save(q:Question,value:Value,pos=index){if(!token)return;setSaving(true);setOffline(false);try{await api.put(`/public/sessions/${token}/answers`,{questionId:q.id,value,position:pos})}catch{setOffline(true)}finally{setSaving(false)}}
function choose(q:Question,value:Value){setAnswers(a=>({...a,[q.id]:value}));window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>save(q,value),250)}
async function next(){if(!survey)return;if(index===survey.questions.length-1){await api.post(`/public/sessions/${token}/complete`);localStorage.removeItem(`survey_session_${slug}`);setDone(true)}else setIndex(i=>i+1)}
const q=survey?.questions[index],value=q?answers[q.id]:undefined;const valid=useMemo(()=>value!==undefined&&value!==''&&(!Array.isArray(value)||value.length>0),[value]);
if(!survey)return <Page><Shell><Header><Leaf/> mindresearch</Header><p>Загружаем опрос…</p></Shell></Page>;
if(done)return <Page><Shell><Welcome><Leaf size={34}/><h1>Спасибо за ваши ответы</h1><p>Анкета успешно сохранена. Вы можете закрыть эту страницу.</p></Welcome></Shell></Page>;
if(!started)return <Page><Shell><Header><Leaf/> mindresearch</Header><Welcome><span>Анонимное исследование</span><h1>{survey.welcomeTitle}</h1><p>{survey.welcomeText}</p><div className="meta"><span>{survey.questions.length} вопросов</span><span>≈ 30 минут</span><span>Можно прерваться</span></div><Button onClick={start}>Начать спокойно <ArrowRight size={18}/></Button></Welcome></Shell></Page>;
return <Page><Shell><Top><Header><Leaf/> mindresearch</Header><Bar><i style={{width:`${((index+1)/survey.questions.length)*100}%`}}/></Bar></Top>{q&&<QuestionCard><span className="eyebrow">Вопрос {index+1} из {survey.questions.length}</span><div className="question">{q.text}</div>{(q.type==='single'||q.type==='multiple')&&<Options>{q.options?.map(o=>{const active=q.type==='multiple'?Array.isArray(value)&&value.includes(o.value):value===o.value;return <Choice key={o.value} $active={active} onClick={()=>choose(q,q.type==='multiple'?(active?(value as string[]).filter(x=>x!==o.value):[...((value as string[])??[]),o.value]):o.value)}><span className="dot">{active&&<Check size={14}/>}</span>{o.label}</Choice>})}</Options>}{(q.type==='text'||q.type==='number')&&<Input autoFocus type={q.type} value={(value as string|number)??''} min={q.validation?.min} max={q.validation?.max} placeholder="Ваш ответ" onChange={e=>choose(q,q.type==='number'?Number(e.target.value):e.target.value)}/>}<Nav><Button aria-label="Назад" disabled={index===0} onClick={()=>setIndex(i=>i-1)} style={{background:'transparent',color:'#526f5b',padding:'12px'}}><ArrowLeft/></Button><span className="save">{offline?<><CloudOff size={14}/> повторим сохранение</>:<><Cloud size={14}/>{saving?'сохраняем…':'сохранено'}</>}</span><Button disabled={!valid||saving} onClick={next}>{index===survey.questions.length-1?'Завершить':'Далее'} <ArrowRight size={18}/></Button></Nav></QuestionCard>}</Shell></Page>}
