import {useEffect,useMemo,useState} from 'react';
import styled from 'styled-components';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Eye,Leaf,X} from 'lucide-react';
import {Button,Card,Page,Shell} from '../ui';

export type PreviewQuestion={id:string;text:string;type:'single'|'multiple'|'text'|'number';required:boolean;options:{value:string;label:string}[];sectionTitle:string};
type PreviewMeta={welcomeTitle:string;welcomeText:string;resultPresentation:{title:string;text:string;showScores:boolean}};
type Value=string|number|string[];

const Layer=styled.div`position:fixed;inset:0;z-index:100;overflow:auto;background:#f3f6f0`;
const PreviewPage=styled(Page)`min-height:100dvh`;
const PreviewShell=styled(Shell)`padding-bottom:60px`;
const Toolbar=styled.div`position:sticky;top:0;z-index:5;margin:0 calc(50% - 50vw);padding:10px max(16px,calc((100vw - 720px)/2));display:flex;align-items:center;justify-content:space-between;gap:14px;background:rgba(246,248,244,.94);border-bottom:1px solid #dce5da;backdrop-filter:blur(14px);.context{display:flex;align-items:center;gap:9px;color:#526f5b;font-size:12px}.context b{display:block;color:#344d3b;font-size:13px}.close{display:inline-flex;align-items:center;gap:7px;padding:10px 13px;border:1px solid #cbd8cb;border-radius:11px;background:#fff;color:#405b48;font-weight:750}`;
const Brand=styled.header`padding:24px 0 10px;display:flex;align-items:center;gap:10px;color:#526f5b;font-weight:750`;
const Welcome=styled(Card)`margin:6vh auto 0;padding:clamp(28px,7vw,56px);h1{font:500 clamp(34px,7vw,54px)/1.08 var(--font-heading),serif;margin:18px 0;color:#2f4938}p{font-size:17px;line-height:1.65;color:#5d6b61;white-space:pre-line}.meta{display:flex;gap:18px;color:#728077;font-size:14px;margin:26px 0;flex-wrap:wrap}.empty{padding:12px 14px;border-radius:12px;background:#f4efe3;color:#766847;font-size:13px}`;
const Progress=styled.div`position:sticky;top:61px;padding:10px 0;background:rgba(243,246,240,.9);backdrop-filter:blur(12px);z-index:2;.line{height:5px;background:#dfe7dc;border-radius:9px;overflow:hidden}.line i{display:block;height:100%;background:#6e8e76;transition:width .25s}.caption{display:flex;justify-content:space-between;margin-bottom:7px;color:#748178;font-size:11px}`;
const QuestionCard=styled(Card)`margin:4vh auto 24px;padding:clamp(24px,6vw,48px);min-height:440px;display:flex;flex-direction:column;.eyebrow{color:#738278;font-size:13px}.question{font:500 clamp(25px,5vw,36px)/1.25 var(--font-heading),serif;color:#293c30;margin:18px 0 28px}.hint{margin:-16px 0 24px;color:#6e7f73;font-size:14px}`;
const Options=styled.div`display:grid;gap:10px;margin:auto 0`;
const Choice=styled.button<{$active:boolean}>`text-align:left;display:flex;align-items:center;gap:13px;width:100%;padding:15px 16px;border-radius:16px;border:1px solid ${p=>p.$active?'#78977f':'#dbe3da'};background:${p=>p.$active?'#e5eee3':'#fff'};color:#304036;min-height:54px;.dot{width:22px;height:22px;border-radius:50%;border:1px solid #9bab9e;display:grid;place-items:center;flex:none;background:${p=>p.$active?'#65836d':'transparent'};color:white}`;
const Input=styled.input`width:100%;border:0;border-bottom:2px solid #b8c7ba;background:transparent;padding:14px 4px;font-size:20px;color:#293c30;outline:none;&:focus{border-color:#607f68}`;
const Nav=styled.div`display:flex;align-items:center;justify-content:space-between;margin-top:30px;gap:10px;.back{background:transparent;color:#526f5b;padding:12px}.preview-note{color:#839087;font-size:11px;text-align:center}`;
const Done=styled(Card)`margin:6vh auto 0;padding:clamp(28px,7vw,56px);background:linear-gradient(145deg,#fff,#f4f8f1);.badge{display:inline-flex;align-items:center;gap:6px;padding:6px 10px;border-radius:999px;background:#e4eee1;color:#55755e;font-size:12px}h1{font:500 clamp(34px,7vw,52px)/1.1 var(--font-heading),serif;color:#304a38;margin:20px 0 10px}p{color:#65736a;font-size:16px;line-height:1.6;white-space:pre-line}.scores{margin-top:24px;padding:15px;border:1px dashed #b8c9b7;border-radius:14px;color:#718078;font-size:13px}`;

export function BuilderPreview({meta,questions,onClose}:{meta:PreviewMeta;questions:PreviewQuestion[];onClose:()=>void}){
  const[screen,setScreen]=useState<'welcome'|'questions'|'done'>('welcome');
  const[index,setIndex]=useState(0);
  const[answers,setAnswers]=useState<Record<string,Value>>({});
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[]);
  const question=questions[index],value=question?answers[question.id]:undefined;
  const valid=useMemo(()=>value!==undefined&&value!==''&&(!Array.isArray(value)||value.length>0),[value]);
  const next=()=>index>=questions.length-1?setScreen('done'):setIndex(current=>current+1);
  const chooseSingle=(value:string)=>{if(!question)return;setAnswers(current=>({...current,[question.id]:value}));window.setTimeout(next,280)};
  return <Layer><PreviewPage><PreviewShell>
    <Toolbar><div className="context"><Eye size={18}/><span><b>Предпросмотр опроса</b>Ответы здесь не сохраняются</span></div><button className="close" onClick={onClose}><X size={16}/> Вернуться к редактированию</button></Toolbar>
    <Brand><Leaf/> mindresearch</Brand>
    {screen==='welcome'&&<Welcome><span>Анонимное исследование</span><h1>{meta.welcomeTitle||'Заголовок приветствия'}</h1><p>{meta.welcomeText||'Здесь появится текст перед началом опроса.'}</p><div className="meta"><span>{questions.length} вопросов</span><span>Можно прерваться</span></div>{questions.length?<Button onClick={()=>setScreen('questions')}>Начать <ArrowRight size={18}/></Button>:<div className="empty">В опросе пока нет вопросов. Вернитесь к редактированию и добавьте методику или собственный тест.</div>}</Welcome>}
    {screen==='questions'&&question&&<><Progress><div className="caption"><span>{question.sectionTitle}</span><span>{index+1} из {questions.length}</span></div><div className="line"><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div></Progress><QuestionCard><span className="eyebrow">Вопрос {index+1} из {questions.length}</span><div className="question">{question.text||'Текст вопроса'}</div>{question.type==='multiple'&&<div className="hint">Можно выбрать несколько вариантов</div>}{(question.type==='single'||question.type==='multiple')&&<Options>{question.options.map(option=>{const active=question.type==='multiple'?Array.isArray(value)&&value.includes(option.value):value===option.value;return <Choice key={option.value} $active={active} onClick={()=>question.type==='single'?chooseSingle(option.value):setAnswers(current=>({...current,[question.id]:active?(value as string[]).filter(item=>item!==option.value):[...((value as string[])??[]),option.value]}))}><span className="dot">{active&&<Check size={14}/>}</span>{option.label||'Вариант ответа'}</Choice>})}</Options>}{(question.type==='text'||question.type==='number')&&<Input autoFocus type={question.type} value={(value as string|number)??''} placeholder="Ваш ответ" onChange={event=>setAnswers(current=>({...current,[question.id]:question.type==='number'?Number(event.target.value):event.target.value}))}/>}<Nav><Button className="back" disabled={index===0} onClick={()=>setIndex(current=>current-1)} aria-label="Назад"><ArrowLeft/></Button><span className="preview-note">Режим предпросмотра</span>{question.type!=='single'&&<Button disabled={!valid} onClick={next}>{index===questions.length-1?'Завершить':'Готово'} <ArrowRight size={18}/></Button>}</Nav></QuestionCard></>}
    {screen==='done'&&<Done><span className="badge"><CheckCircle2 size={15}/> Опрос завершён</span><h1>{meta.resultPresentation.title||'Спасибо за ваши ответы'}</h1><p>{meta.resultPresentation.text||'Ваши ответы сохранены.'}</p>{meta.resultPresentation.showScores&&<div className="scores">Здесь будут показаны рассчитанные результаты добавленных подтверждённых методик.</div>}<Button style={{marginTop:24}} onClick={onClose}>Вернуться к редактированию</Button></Done>}
  </PreviewShell></PreviewPage></Layer>
}
