export const demoUser={id:'demo',name:'Евгения',email:'mgodagov@vk.com',role:'researcher',bio:'Психолог и исследователь. Изучаю пищевое поведение, отношение к себе и саморегуляцию.',avatarUrl:'',publicSlug:'evgeniya',isProfilePublic:false};
export const demoSurveys=[{id:'demo-survey',slug:'anketa',title:'Анкета',status:'active',responses:24,completed:18,description:'Исследование пищевого поведения и саморегуляции'},{id:'demo-draft',slug:'wellbeing',title:'Самочувствие и поддержка',status:'draft',responses:0,completed:0,description:'Черновик нового исследования'}];
export const demoInstruments=[
  {id:'test-1',code:'test_1',title:'MSPSS — многомерная шкала социальной поддержки',description:'Оценка воспринимаемой поддержки семьи, друзей и значимых людей.',questionCount:12,isVerified:true,scoringCode:'test_1',author:'Gregory Zimet, Nancy Dahlem, Sara Zimet, Gordon Farley'},
  {id:'test-2',code:'test_2',title:'ССПМ-2011',description:'Стиль саморегуляции поведения.',questionCount:52,isVerified:true,scoringCode:'test_2',author:'В. И. Моросанова, Н. Г. Кондратюк'},
  {id:'test-3',code:'test_3',title:'Шкала ясности Я-концепции, SCCS',description:'Ясность и устойчивость представления человека о себе.',questionCount:12,isVerified:true,scoringCode:'test_3',author:'Jennifer Campbell и соавторы'},
  {id:'test-4',code:'test_4',title:'NSPS',description:'Негативный образ себя и социальная тревога.',questionCount:27,isVerified:true,scoringCode:'test_4',author:'David Moscovitch, Keith Huyder'},
  {id:'test-5',code:'test_5',title:'ШОПП',description:'Семь аспектов пищевого поведения и отношения к телу.',questionCount:51,isVerified:true,scoringCode:'test_5',author:'David Garner, Marion Olmsted, Janet Polivy'},
  {id:'test-6',code:'test_6',title:'DEBQ',description:'Ограничительное, эмоциогенное и экстернальное пищевое поведение.',questionCount:33,isVerified:true,scoringCode:'test_6',author:'Tatjana van Strien и соавторы'},
];
export const demoMethodologies:Record<string,any>={
  test_1:{code:'test_1',title:'MSPSS',version:'mspss-zimet-v1',summary:'Шкала измеряет субъективно воспринимаемую поддержку семьи, друзей и значимого другого.',steps:['Ответы оцениваются от 1 до 7.','Для каждой субшкалы и общего показателя рассчитывается среднее значение.'],notes:['Чем выше балл, тем выше воспринимаемая поддержка.'],sources:[{title:'Zimet et al. — оригинальная публикация MSPSS (1988)',url:'https://doi.org/10.1207/s15327752jpa5201_2'}]},
  test_2:{code:'test_2',title:'ССПМ-2011',version:'sspm-2011-v1',summary:'Опросник оценивает регуляторные процессы и общий уровень осознанной саморегуляции.',steps:['Ответы преобразуются в группы «Да» и «Нет».','За совпадение с ключом начисляется один балл.','Результаты суммируются отдельно по шкалам.'],notes:['Используется ключ 52-пунктовой версии ССПМ-2011.'],sources:[{title:'Моросанова В. И., Кондратюк Н. Г. — новая версия ССПМ',url:'https://lib.mgppu.ru/OpacUnicode/index.php?url=%2Fnotices%2Findex%2FIdNotice%3A90946%2FSource%3Adefault'}]},
  test_3:{code:'test_3',title:'SCCS',version:'sccs-ru-2021-v1',summary:'Однофакторная шкала ясности и устойчивости представления человека о себе.',steps:['Десять пунктов реверсируются.','Рассчитываются сумма и средний балл 12 пунктов.'],notes:['Высокий результат означает более ясную Я-концепцию.'],sources:[{title:'Campbell et al. — оригинальная публикация SCCS (1996)',url:'https://doi.org/10.1037/0022-3514.70.1.141'}]},
  test_4:{code:'test_4',title:'NSPS',version:'nsps-moscovitch-huyder-v1',summary:'Шкала оценивает обеспокоенность воспринимаемыми недостатками в социальных ситуациях.',steps:['Все 27 ответов используются напрямую.','Баллы суммируются по трём субшкалам и в общий показатель.'],notes:['У шкалы нет универсальных диагностических границ.'],sources:[{title:'Moscovitch & Huyder — оригинальная публикация NSPS (2011)',url:'https://doi.org/10.1016/j.beth.2010.04.007'}]},
  test_5:{code:'test_5',title:'ШОПП / EDI',version:'shopp-ru-2011-v1',summary:'Семь самостоятельных субшкал пищевого поведения и отношения к телу.',steps:['Прямые и обратные пункты оцениваются по ключу.','Баллы суммируются отдельно внутри каждой субшкалы.'],notes:['Общий суммарный показатель не рассчитывается.'],sources:[{title:'Garner, Olmsted, Polivy — разработка EDI',url:'https://doi.org/10.1002/1098-108X(198321)2:2%3C15::AID-EAT2260020203%3E3.0.CO;2-6'}]},
  test_6:{code:'test_6',title:'DEBQ',version:'debq-van-strien-v2',summary:'Три независимых показателя: ограничительное, эмоциогенное и экстернальное пищевое поведение.',steps:['Ответы оцениваются от 1 до 5.','Пункт 31 реверсируется.','По каждой шкале рассчитывается среднее.'],notes:['Общий показатель по всем пунктам не рассчитывается.'],sources:[{title:'van Strien et al. — оригинальная разработка DEBQ (1986)',url:'https://doi.org/10.1002/1098-108X(198602)5:2%3C295::AID-EAT2260050209%3E3.0.CO;2-T'}]},
};
