export const demoUser={id:'demo',name:'Евгения',email:'mgodagov@vk.com',role:'researcher',bio:'Психолог и исследователь. Изучаю пищевое поведение, отношение к себе и саморегуляцию.',avatarUrl:'',publicSlug:'evgeniya',isProfilePublic:false};
export const demoSurveys=[{id:'demo-survey',slug:'anketa',title:'Анкета',status:'active',responses:24,completed:18,description:'Исследование пищевого поведения и саморегуляции'},{id:'demo-draft',slug:'wellbeing',title:'Самочувствие и поддержка',status:'draft',responses:0,completed:0,description:'Черновик нового исследования'}];
export const demoInstruments=[
  {id:'test-1',code:'test_1',title:'MSPSS — многомерная шкала социальной поддержки',description:'Оценка воспринимаемой поддержки семьи, друзей и значимых людей.',questionCount:12,isVerified:true,scoringCode:'test_1',author:'Gregory Zimet, Nancy Dahlem, Sara Zimet, Gordon Farley'},
  {id:'test-2',code:'test_2',title:'ССПМ-2011',description:'Стиль саморегуляции поведения.',questionCount:52,isVerified:true,scoringCode:'test_2',author:'В. И. Моросанова, Н. Г. Кондратюк'},
  {id:'test-3',code:'test_3',title:'Шкала ясности Я-концепции, SCCS',description:'Ясность и устойчивость представления человека о себе.',questionCount:12,isVerified:true,scoringCode:'test_3',author:'Jennifer Campbell и соавторы'},
  {id:'test-4',code:'test_4',title:'NSPS',description:'Негативный образ себя и социальная тревога.',questionCount:27,isVerified:true,scoringCode:'test_4',author:'David Moscovitch, Keith Huyder'},
  {id:'test-5',code:'test_5',title:'ШОПП',description:'Семь аспектов пищевого поведения и отношения к телу.',questionCount:51,isVerified:true,scoringCode:'test_5',author:'David Garner, Marion Olmsted, Janet Polivy'},
  {id:'test-6',code:'test_6',title:'DEBQ',description:'Ограничительное, эмоциогенное и экстернальное пищевое поведение.',questionCount:33,isVerified:true,scoringCode:'test_6',author:'Tatjana van Strien и соавторы'},
  {id:'test-7',code:'test_7',title:'Шкала академической мотивации, ШАМ',description:'Семь типов академической мотивации студентов.',questionCount:28,isVerified:true,scoringCode:'test_7',author:'Т. О. Гордеева, О. А. Сычев, Е. Н. Осин'},
  {id:'test-8',code:'test_8',title:'Academic Motivation Scale, AMS-C 28',description:'Official English College Version for research purposes.',questionCount:28,isVerified:true,scoringCode:'test_8',author:'Robert J. Vallerand et al.'},
  {id:'test-9',code:'test_9',title:'Шкала отчуждения от учебы',description:'Четыре формы отчуждения от учебной деятельности.',questionCount:12,isVerified:true,scoringCode:'test_9',author:'Е. Н. Осин'},
  {id:'test-10',code:'test_10',title:'General Procrastination Scale, GPS — Student Form',description:'Original English 20-item student form.',questionCount:20,isVerified:true,scoringCode:'test_10',author:'Clarry H. Lay'},
  {id:'test-11',code:'test_11',title:'Pure Procrastination Scale, PPS-12',description:'Original English 12-item scale.',questionCount:12,isVerified:true,scoringCode:'test_11',author:'Piers Steel'},
  {id:'test-12',code:'test_12',title:'Big Five Inventory–2, BFI-2 — русская версия',description:'Пять личностных областей и 15 аспектов.',questionCount:60,isVerified:true,scoringCode:'test_12',author:'Christopher J. Soto, Oliver P. John; С. А. Щебетенко и соавторы'},
  {id:'test-13',code:'test_13',title:'Краткая версия Big Five Inventory–2, BFI-2-S — русская версия',description:'Пять личностных областей и 15 аспектов в 30 пунктах.',questionCount:30,isVerified:true,scoringCode:'test_13',author:'Christopher J. Soto, Oliver P. John; А. М. Мишкевич и соавторы'},
  {id:'test-14',code:'test_14',title:'Краткий пятифакторный опросник личности, TIPI-RU',description:'Пять областей личности по двум пунктам.',questionCount:10,isVerified:true,scoringCode:'test_14',author:'Samuel D. Gosling, Peter J. Rentfrow, William B. Swann Jr.; А. С. Сергеева и соавторы'},
  {id:'test-15',code:'test_15',title:'IPIP-NEO-120 — public-domain five-factor inventory',description:'Original English 120-item public-domain Big Five domains and 30 facets.',questionCount:120,isVerified:true,scoringCode:'test_15',author:'John A. Johnson; Lewis R. Goldberg and IPIP collaborators'},
  {id:'test-16',code:'test_16',title:'Mini-IPIP — 20-item public-domain Big Five inventory',description:'Original English 20-item public-domain Big Five short form.',questionCount:20,isVerified:true,scoringCode:'test_16',author:'M. Brent Donnellan, Frederick L. Oswald, Brendan M. Baird, Richard E. Lucas'},
];
export {methodologies as demoMethodologies} from '../../../api/src/scoring/methodologies';
