import{useEffect,useState}from'react';
import{Link}from'react-router-dom';
import styled from'styled-components';
import{ArrowRight,BarChart3,CheckCircle2,Clock3,Copy,ExternalLink,Pencil,Plus}from'lucide-react';
import{api}from'../api';import{Button,Card}from'../ui';import{demoSurveys,demoUser}from'./demo';import{PlatformLayout}from'./Layout';
type Survey={id:string;slug:string;title:string;status:string;responses:number;completed:number;description?:string};
const Head=styled.div`display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:28px;h1{font:500 clamp(32px,5vw,46px) Georgia,serif;margin:7px 0;color:#304a38}.hello{color:#758178}a{text-decoration:none}`;
const Grid=styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;@media(max-width:720px){grid-template-columns:1fr}`;
const SurveyCard=styled(Card)`padding:23px;border-radius:20px;h2{font:600 21px Georgia,serif;margin:8px 0;color:#344e3c}.status{display:inline-flex;align-items:center;gap:5px;font-size:11px;color:#52705a;background:#e4eee1;padding:5px 8px;border-radius:20px}.draft{background:#f0eee5;color:#7d7255}.description{color:#78847b;min-height:42px;font-size:13px;line-height:1.5}.metrics{display:flex;gap:18px;margin:20px 0;color:#68776d;font-size:12px}.metrics span{display:flex;gap:5px;align-items:center}.actions{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #e7ece5;padding-top:15px;gap:10px;flex-wrap:wrap}.links{display:flex;gap:7px;align-items:center}a,.copy{color:#45624e;text-decoration:none;font-weight:700;font-size:13px;display:flex;align-items:center;gap:5px}.copy{border:0;background:#edf3eb;padding:8px 10px;border-radius:9px;cursor:pointer}`;
export function PlatformHome(){
  const[surveys,setSurveys]=useState<Survey[]>([]),[name,setName]=useState(''),[copied,setCopied]=useState('');
  useEffect(()=>{Promise.all([api.get('/admin/surveys'),api.get('/account/me')]).then(([s,u])=>{setSurveys(s.data);setName(u.data.name)}).catch(()=>{if(import.meta.env.DEV){setSurveys(demoSurveys);setName(demoUser.name)}})},[]);
  const copy=async(s:Survey)=>{await navigator.clipboard.writeText(`${location.origin}/s/${s.slug}`);setCopied(s.id);setTimeout(()=>setCopied(''),1800)};
  return <PlatformLayout><Head><div><span className="hello">Здравствуйте{name?`, ${name}`:''}</span><h1>Ваши опросы</h1></div><Link to="/app/surveys/new"><Button><Plus size={17}/> Новый опрос</Button></Link></Head><Grid>{surveys.map(s=><SurveyCard key={s.id}><span className={`status ${s.status==='draft'?'draft':''}`}>{s.status==='active'?<CheckCircle2 size={12}/>:<Clock3 size={12}/>} {s.status==='active'?'Опубликован':'Черновик'}</span><h2>{s.title}</h2><div className="description">{s.description||'Описание пока не добавлено'}</div><div className="metrics"><span><BarChart3 size={14}/>{s.responses} прохождений</span><span><CheckCircle2 size={14}/>{s.completed} завершено</span></div><div className="actions"><div className="links"><button className="copy" onClick={()=>copy(s)}><Copy size={14}/>{copied===s.id?'Скопировано':'Скопировать ссылку'}</button><a href={`/s/${s.slug}`} target="_blank" aria-label="Открыть опрос"><ExternalLink size={15}/></a><Link to={`/app/surveys/${s.id}/edit`}><Pencil size={14}/> Редактировать</Link></div><Link to={`/app/surveys/${s.id}/results`}>Статистика <ArrowRight size={14}/></Link></div></SurveyCard>)}</Grid></PlatformLayout>
}
