import{useEffect,useState,type ReactNode}from'react';
import{NavLink,useNavigate}from'react-router-dom';
import styled from'styled-components';
import{ClipboardList,Leaf,LogOut,Plus,Send,ShieldCheck,UserRound}from'lucide-react';
import{api}from'../api';
const Frame=styled.div`min-height:100dvh;background:#f3f6f0;display:grid;grid-template-columns:240px 1fr;@media(max-width:760px){grid-template-columns:1fr;padding-bottom:74px}`;
const Side=styled.aside`padding:28px 18px;border-right:1px solid #dfe7dc;background:rgba(250,252,248,.92);position:sticky;top:0;height:100dvh;.brand{display:flex;align-items:center;gap:9px;color:#3e5e48;font-weight:800;padding:0 10px 28px}.nav{display:grid;gap:5px}a,button{border:0;text-decoration:none;background:transparent;color:#68766c;display:flex;align-items:center;gap:10px;padding:12px;border-radius:12px;font-weight:650;font-size:14px}a.active,a:hover{background:#e6eee3;color:#3d5c46}.logout{position:absolute;bottom:22px;left:18px;right:18px}@media(max-width:760px){position:fixed;z-index:10;top:auto;bottom:0;width:100%;height:68px;border-right:0;border-top:1px solid #dfe7dc;padding:8px;.brand,.logout{display:none}.nav{display:grid;grid-template-columns:repeat(4,1fr)}a{justify-content:center;flex-direction:column;gap:2px;padding:5px;font-size:10px}}`;
const Main=styled.main`width:min(100% - 36px,1180px);margin:0 auto;padding:34px 0 70px;`;
export function PlatformLayout({children}:{children:ReactNode}){const nav=useNavigate();const[role,setRole]=useState('');useEffect(()=>{api.get('/account/me').then(r=>setRole(r.data.role)).catch(()=>{})},[]);return <Frame><Side><div className="brand"><Leaf/> mindresearch</div><div className="nav"><NavLink to="/app" end><ClipboardList size={18}/> Мои опросы</NavLink><NavLink to="/app/surveys/new"><Plus size={18}/> Создать</NavLink><NavLink to="/app/methodologies/suggest"><Send size={18}/> Предложить тест</NavLink>{['owner','admin'].includes(role)&&<NavLink to="/app/methodologies/review"><ShieldCheck size={18}/> Проверка</NavLink>}<NavLink to="/app/profile"><UserRound size={18}/> Профиль</NavLink></div><button className="logout" onClick={()=>{localStorage.removeItem('admin_token');nav('/login')}}><LogOut size={17}/> Выйти</button></Side><Main>{children}</Main></Frame>}
