import{useEffect,useMemo,useState}from'react';import{useNavigate}from'react-router-dom';import styled from'styled-components';import{BarChart3,CheckCircle2,Clock3,Copy,Leaf,LogOut,Users}from'lucide-react';import{Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';import{createColumnHelper,flexRender,getCoreRowModel,useReactTable}from'@tanstack/react-table';import{api}from'../api';import type{SessionRow}from'../types';import{Button,Card,Page}from'../ui';
const Wrap=styled.div`width:min(100% - 32px,1180px);margin:auto;padding-bottom:60px`;
const Header=styled.header`display:flex;align-items:center;justify-content:space-between;padding:26px 0;.brand{display:flex;gap:10px;align-items:center;font-weight:800;color:#496452}button{border:0;background:none;color:#68776d}`;
const Grid=styled.div`display:grid;grid-template-columns:repeat(3,1fr);gap:16px;@media(max-width:700px){grid-template-columns:1fr}`;
const Stat=styled(Card)`padding:22px;display:flex;gap:15px;align-items:center;b{display:block;font-size:28px;color:#31493a}span{color:#758178;font-size:13px}`;
const Panel=styled(Card)`padding:24px;margin-top:18px;overflow:hidden;h2{font:500 24px Georgia,serif;margin:0 0 20px}.toolbar{display:flex;gap:12px;justify-content:space-between;align-items:center;flex-wrap:wrap}.link{padding:10px 13px;background:#edf2eb;border-radius:12px;color:#496452;font-size:13px}`;
const Table=styled.table`width:100%;border-collapse:collapse;margin-top:14px;th,td{text-align:left;padding:13px 10px;border-bottom:1px solid #edf0eb;font-size:14px}th{color:#78837b;font-weight:600}.pill{padding:5px 9px;border-radius:20px;background:#e7efe5;color:#4e6b56;font-size:12px}`;
type SurveyRow={id:string;slug:string;title:string;responses:number;completed:number};type Result={sessions:SessionRow[];distribution:{code:string;text:string;value:string|number;count:number}[]};const helper=createColumnHelper<SessionRow>();
export function Dashboard(){const nav=useNavigate();const[surveys,setSurveys]=useState<SurveyRow[]>([]);const[result,setResult]=useState<Result>({sessions:[],distribution:[]});const[selectedQuestion,setSelectedQuestion]=useState('');
useEffect(()=>{api.get('/admin/surveys').then(async r=>{setSurveys(r.data);if(r.data[0]){const x=await api.get(`/admin/surveys/${r.data[0].id}/results`);setResult(x.data)}}).catch(()=>nav('/admin/login'))},[nav]);
const survey=surveys[0];const questions=useMemo(()=>[...new Map(result.distribution.map(x=>[x.code,x.text])).entries()],[result]);useEffect(()=>{if(!selectedQuestion&&questions[0])setSelectedQuestion(questions[0][0])},[questions,selectedQuestion]);const chart=result.distribution.filter(x=>x.code===selectedQuestion).map(x=>({answer:String(x.value).replace(/^"|"$/g,''),count:x.count}));
const columns=useMemo(()=>[helper.accessor('status',{header:'Статус',cell:x=><span className="pill">{x.getValue()==='completed'?'Завершена':'В процессе'}</span>}),helper.accessor('startedAt',{header:'Начата',cell:x=>new Date(x.getValue()).toLocaleString('ru')}),helper.accessor('answered',{header:'Ответов'}),helper.accessor('lastActivityAt',{header:'Активность',cell:x=>new Date(x.getValue()).toLocaleString('ru')})],[]);const table=useReactTable({data:result.sessions,columns,getCoreRowModel:getCoreRowModel()});
const completed=result.sessions.filter(x=>x.status==='completed').length;return <Page><Wrap><Header><div className="brand"><Leaf/> Опора · кабинет</div><button onClick={()=>{localStorage.removeItem('admin_token');nav('/admin/login')}}><LogOut size={18}/></button></Header><h1>{survey?.title??'Исследование'}</h1><Grid><Stat><Users/><div><b>{result.sessions.length}</b><span>всего участников</span></div></Stat><Stat><CheckCircle2/><div><b>{completed}</b><span>завершили</span></div></Stat><Stat><Clock3/><div><b>{result.sessions.length?Math.round(completed/result.sessions.length*100):0}%</b><span>завершаемость</span></div></Stat></Grid><Panel><div className="toolbar"><h2>Ссылка для участников</h2><Button onClick={()=>navigator.clipboard.writeText(`${location.origin}/s/${survey?.slug}`)}><Copy size={16}/> Скопировать</Button></div><div className="link">{location.origin}/s/{survey?.slug}</div></Panel><Panel><div className="toolbar"><h2><BarChart3 size={20}/> Распределение ответов</h2><select value={selectedQuestion} onChange={e=>setSelectedQuestion(e.target.value)}>{questions.map(([code,text])=><option key={code} value={code}>{text}</option>)}</select></div><div style={{height:300,marginTop:20}}><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="answer" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#6e8e76" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel><h2>Прохождения</h2><div style={{overflowX:'auto'}}><Table><thead>{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id}>{flexRender(h.column.columnDef.header,h.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id}>{r.getVisibleCells().map(c=><td key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></Table></div></Panel></Wrap></Page>}
