export const RESPONDENT_RESULTS_COPY = {
  title: "Результаты респондентов",
  delete: "Удалить",
  export: "Экспортировать",
  preparing: "Подготовка…",
  selectAll: "Выбрать всех респондентов",
  respondent: "Респондент",
  status: "Статус",
  answers: "Ответы",
  started: "Начато",
  showAnswers: "Показать ответы",
  completed: "Завершена",
  inProgress: "В процессе",
  trash: "Корзина",
  deletedTitle: "Удалённые результаты",
  restore: "Восстановить",
  deletedAt: "Удалено",
  emptyTrash: "Корзина пуста",
} as const;
