import { QUALITY_V2_CONFIG, type QualityConfig } from './config.js';
import { mean, median, quantile, sd, variance, spearman, pearson, random, ranks } from './math.js';
import { normalized } from './keys.js';
import { scaleGroups } from './psychometrics.js';
import { scoreMspss } from '../scoring/mspss.js';
import { scoreSspm2011 } from '../scoring/sspm2011.js';
import { scoreSccs } from '../scoring/sccs.js';
import { scoreNsps } from '../scoring/nsps.js';
import { scoreShopp } from '../scoring/shopp.js';
import { scoreDebq } from '../scoring/debq.js';
import type { Item, Participant, QualityV2 } from './types.js';
export function describe(x:number[]){return{n:x.length,mean:mean(x),median:median(x),sd:sd(x),iqr:x.length?quantile(x,.75)!-quantile(x,.25)!:null,percentiles:Object.fromEntries([.01,.05,.1,.25,.5,.75,.9,.95,.99].map(p=>[`P${String(Math.round(p*100)).padStart(2,'0')}`,quantile(x,p)]))};}
export function alpha(rows:number[][]){if(rows.length<2||!rows[0]||rows[0].length<2)return null;const k=rows[0].length,total=variance(rows.map(r=>r.reduce((a,b)=>a+b,0)));return total!==null&&total>0?k/(k-1)*(1-rows[0].reduce((s,_,i)=>s+(variance(rows.map(r=>r[i]))??0),0)/total):null;}
export function mannWhitney(a:number[],b:number[]){if(!a.length||!b.length)return{u:null,rank_biserial:null};const r=ranks([...a,...b]),u=r.slice(0,a.length).reduce((s,v)=>s+v,0)-a.length*(a.length+1)/2;return{u,rank_biserial:2*u/(a.length*b.length)-1};}
function actualScales(person:Participant,items:Item[]){const out:Record<string,number>={};for(const instrument of ['test_1','test_2','test_3','test_4','test_5','test_6']){const raw=new Map<number,number>();for(const i of items.filter(i=>i.instrument===instrument)){const n=Number(i.code.match(/(\d+)$/)?.[1]),v=Number(person.answers[i.id]?.value);if(n&&Number.isFinite(v))raw.set(n,v)}const result=instrument==='test_1'?scoreMspss(raw):instrument==='test_2'?scoreSspm2011(raw):instrument==='test_3'?scoreSccs(raw):instrument==='test_4'?scoreNsps(raw):instrument==='test_5'?scoreShopp(raw):scoreDebq(raw);if(!result)continue;const generic=result as unknown as {average?:number;overall?:{score:number};scales?:Record<string,{average?:number;score?:number}>};if(generic.average!==undefined)out[`${instrument}:overall`]=generic.average;if(generic.overall)out[`${instrument}:overall`]=generic.overall.score;for(const[key,scale]of Object.entries(generic.scales??{}))out[`${instrument}:${key}`]=scale.average??scale.score!;}return out;}
export function datasetDiagnostics(items:Item[],people:Participant[],qualities:Record<string,QualityV2>,config:QualityConfig=QUALITY_V2_CONFIG){
  const completed=people.filter(p=>p.status==='completed'),cohorts:Record<string,Participant[]>={all:completed,trusted:completed.filter(p=>p.trusted),public:completed.filter(p=>p.cohort==='public'),unassigned:completed.filter(p=>p.cohort==='unassigned'&&!p.trusted)};
  const scales=[...scaleGroups(items)],scores=new Map(completed.map(p=>[p.id,actualScales(p,items)]));
  const distributions:Record<string,Record<string,ReturnType<typeof describe>>>={},reliability:Record<string,unknown[]>={},correlations:Record<string,unknown[]>={};
  const extract=(p:Participant,name:string):number|null=>{const q=qualities[p.id];if(!q)return null;const value=name==='overall'?q.overall.score:name==='behavioral'?q.behavioral.score:name==='response'?q.response.score:name==='rpr'?q.response.components.rpr?.metrics.rpr:name==='pair_consistency'?q.response.components.pairs?.metrics.pair_consistency:name==='speed'?q.behavioral.metrics.median_ratio:name==='longstring'?Math.max(0,...Object.values(q.response.metrics.patterns as Record<string,{run:number}>??{}).map(v=>v.run)):null;return typeof value==='number'?value:null;};
  for(const[cohort,group]of Object.entries(cohorts)){
    distributions[cohort]=Object.fromEntries(['overall','behavioral','response','rpr','pair_consistency','longstring','speed'].map(name=>[name,describe(group.flatMap(p=>{const v=extract(p,name);return v===null?[]:[v]}))]));
    reliability[cohort]=scales.map(([scale,questions])=>{const observed=group.map(p=>questions.map(i=>normalized(i,p.answers[i.id]?.value,scale))),complete=observed.filter(row=>row.every(v=>v!==null)) as number[][],totals=complete.map(row=>row.reduce((s,v)=>s+v,0));const supported=complete.length>=config.diagnostics.minN;return{scale,label:questions[0].scales.find(s=>s.id===scale)?.label??scale,items:questions.length,missing_rate:observed.length?observed.reduce((s,row)=>s+row.filter(v=>v===null).length,0)/(observed.length*questions.length):null,...describe(group.flatMap(p=>{const v=scores.get(p.id)?.[scale];return typeof v==='number'?[v]:[]})),score_basis:'official_scoring_key',complete_cases:complete.length,alpha:supported?alpha(complete):null,omega:null,omega_reason:'Omega не рассчитана: для неё нужна проверенная факторная модель, а не приближение из alpha',corrected_item_total:questions.map((item,index)=>({question_id:item.id,question:item.text,distribution:Object.fromEntries(item.options.map(o=>[o.label,group.filter(p=>String(p.answers[item.id]?.value)===String(o.value)).length])),missing:group.filter(p=>normalized(item,p.answers[item.id]?.value,scale)===null).length,correlation:supported?pearson(complete.map(r=>r[index]),complete.map(r=>r.reduce((s,v,i)=>s+(i===index?0:v),0))):null}))};});
    correlations[cohort]=config.diagnostics.crossPairs.map(([a,b,expected])=>{const pairs=group.flatMap(p=>{const s=scores.get(p.id)!;return s[a]!==undefined&&s[b]!==undefined?[[s[a],s[b]]]:[]}),x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]);if(pairs.length<config.diagnostics.minN)return{a,b,expected,n:pairs.length,rho:null,ci:null};const rng=random(`${config.seed}:${cohort}:${a}:${b}`),boots:number[]=[];for(let k=0;k<config.diagnostics.bootstrap;k++){const sample=Array.from({length:pairs.length},()=>pairs[Math.floor(rng()*pairs.length)]),r=spearman(sample.map(p=>p[0]),sample.map(p=>p[1]));if(r!==null)boots.push(r)}return{a,b,expected,n:pairs.length,rho:spearman(x,y),ci:boots.length?[quantile(boots,.025),quantile(boots,.975)]:null};});
  }
  const comparison=Object.fromEntries(['overall','behavioral','response','rpr','pair_consistency','longstring','speed'].map(name=>{const a=cohorts.trusted.flatMap(p=>{const v=extract(p,name);return v===null?[]:[v]}),b=cohorts.public.flatMap(p=>{const v=extract(p,name);return v===null?[]:[v]});return[name,{trusted:describe(a),public:describe(b),...mannWhitney(a,b)}]}));
  return{version:2,generated_at:new Date().toISOString(),distributions,reliability,correlations,cohort_comparison:comparison,lowest_scores:completed.filter(p=>qualities[p.id]?.overall.score!==null&&qualities[p.id]).sort((a,b)=>qualities[a.id].overall.score!-qualities[b.id].overall.score!).slice(0,20).map(p=>({id:p.id,alias:p.alias,cohort:p.cohort,overall:qualities[p.id].overall.score,behavioral:qualities[p.id].behavioral.score,response:qualities[p.id].response.score,confidence:qualities[p.id].overall.confidence,flags:qualities[p.id].overall.flags})),note:'Диагностический отчёт для ручной проверки. Данные не удаляются; alpha и групповые корреляции не входят в индивидуальные индексы.'};
}
