import { QUALITY_V2_CONFIG, type QualityConfig } from './config.js';
import { clamp, geometric, hash, mean, median, severity, stats, calibratedScore } from './math.js';
import { patterns, rpr, pairConsistency, lowerTailPercentile } from './psychometrics.js';
import type { Baseline, Component, Flag, Index, Item, Participant, QualityV2, ReferenceModel, QualityStatus } from './types.js';

export function statusFor(score:number|null,config:QualityConfig):QualityStatus{return score===null?'insufficient_data':score>=config.status.high?'high':score>=config.status.acceptable?'acceptable':score>=config.status.review?'review':'high_concern';}
function flag(code:string,domain:Flag['domain'],value:number|null,warning:number,critical:number,explanation:string,config:QualityConfig):Flag[]{if(value===null)return[];const s=severity(value,warning,critical);return s<config.flag.warningSeverity?[]:[{code,domain,value,threshold:critical,explanation,severity:s>=config.flag.strongSeverity?'strong':'warning'}];}
const missing=(reason:string):Component=>({score:null,confidence:0,reason,metrics:{},flags:[]});
function index(components:Record<string,Component>,weights:Record<string,number>,metrics:Record<string,unknown>,confidence:number,baseline:Baseline|null,config:QualityConfig,now:string):Index{const score=geometric(Object.entries(components).map(([key,c])=>({score:c.score,weight:weights[key]??0})),config.epsilon),flags=Object.values(components).flatMap(c=>c.flags);return{score:score===null?null:Math.round(score*100)/100,confidence:score===null?0:clamp(confidence),status:statusFor(score===null?null:Math.round(score*100)/100,config),partial:Object.values(components).some(c=>c.score===null),flags,components,metrics,version:config.version,calculated_at:now,baseline_version:baseline?.version??null};}
export function behavioral(person:Participant,items:Item[],model:ReferenceModel|null,baseline:Baseline|null,config:QualityConfig,now:string):Index{
  const eligible=items.filter(i=>i.psychological&&!i.exclude&&i.attentionExpected===undefined&&person.answers[i.id]),measured=eligible.filter(i=>{const t=person.answers[i.id]?.activeSeconds;return t!=null&&Number.isFinite(t)&&t>=0}),coverage=eligible.length?measured.length/eligible.length:0;
  const rows=measured.flatMap(item=>{const candidates=[model?.time[item.id],model?.blockTime[item.block],model?.typeTime[item.type]],ref=candidates.find(r=>r&&r.n>=config.reference.minQuestionN);if(!ref)return[];const time=person.answers[item.id].activeSeconds!,ratio=(time+config.behavior.offsetSeconds)/(ref.median+config.behavior.offsetSeconds);return[{item,time,median:ref.median,ratio,source:ref===candidates[0]?'question':ref===candidates[1]?'block':'type',n:ref.n,population:ref.source??baseline?.source}]});
  const refCoverage=measured.length?rows.length/measured.length:0,metrics:Record<string,unknown>={telemetry_coverage:coverage,reference_coverage:refCoverage,measured:measured.length,answered:eligible.length,reference_questions:rows.length,question_ratios:Object.fromEntries(rows.map(row=>[row.item.id,{ratio:row.ratio,log_ratio:Math.log(row.ratio),median:row.median,n:row.n,source:row.source,calibration_source:row.population}]))};
  if(coverage<config.behavior.minCoverage||rows.length<config.behavior.minQuestions||person.status!=='completed'){const reason=person.status!=='completed'?'Прохождение ещё не завершено':coverage<config.behavior.minCoverage?'Недостаточное покрытие телеметрией':'Недостаточно reference statistics времени';const out=index({pace:missing(reason),bursts:missing(reason),acceleration:missing(reason),duration:missing(reason)},config.behavior.weights,metrics,0,baseline,config,now);out.flags.push({code:coverage<config.behavior.minCoverage?'INSUFFICIENT_TELEMETRY':'INSUFFICIENT_REFERENCE_DATA',severity:'info',domain:'data',value:coverage,threshold:config.behavior.minCoverage,explanation:reason});return out;}
  const fast=(r:typeof rows[number])=>r.ratio<config.behavior.fastRatio&&r.time<config.behavior.fastSeconds,extreme=(r:typeof rows[number])=>r.ratio<config.behavior.extremeRatio&&r.time<config.behavior.extremeSeconds;
  const medianRatio=median(rows.map(r=>r.ratio))!,fastFraction=rows.filter(fast).length/rows.length,extremeFraction=rows.filter(extreme).length/rows.length,p=config.behavior.pace;
  const paceSeverity=Math.max(severity(medianRatio,p.medianWarning,p.medianCritical),severity(fastFraction,p.fastWarning,p.fastCritical),severity(extremeFraction,p.extremeWarning,p.extremeCritical));
  const pace:Component={score:100*(1-paceSeverity),confidence:coverage*refCoverage,metrics:{median_ratio:medianRatio,fast_fraction:fastFraction,extreme_fast_fraction:extremeFraction},flags:[...flag('BEHAVIOR_FAST_OVERALL','speeding',medianRatio,p.medianWarning,p.medianCritical,'Систематически малое нормализованное время ответов; повод для проверки, не доказательство случайного заполнения',config),...flag('BEHAVIOR_EXTREME_FAST_FRACTION','speeding',extremeFraction,p.extremeWarning,p.extremeCritical,'Заметная доля крайне быстрых ответов относительно reference времени этих вопросов',config)]};
  let run=0,longest=0,runs=0,previous:typeof rows[number]|undefined;for(const row of rows.sort((a,b)=>a.item.order-b.item.order)){const contiguous=previous&&row.item.block===previous.item.block&&row.item.position===previous.item.position+1;if(!contiguous||!fast(row)){if(run>=config.behavior.bursts.minRun)runs++;run=0}if(fast(row))run++;longest=Math.max(longest,run);previous=row}if(run>=config.behavior.bursts.minRun)runs++;
  const bursts:Component={score:100*(1-severity(longest,config.behavior.bursts.warning,config.behavior.bursts.critical)),confidence:coverage*refCoverage,metrics:{longest_fast_run:longest,fast_runs:runs},flags:flag('BEHAVIOR_FAST_RUN','speeding',longest,config.behavior.bursts.warning,config.behavior.bursts.critical,'Длинная серия нормализованно быстрых ответов внутри одной методики',config)};
  const sequenceCoverage=eligible.length?eligible.filter(i=>person.answers[i.id].visitSequence!=null).length/eligible.length:0;metrics.sequence_coverage=sequenceCoverage;
  const ordered=[...eligible].sort((a,b)=>(person.answers[a.id].visitSequence??a.order)-(person.answers[b.id].visitSequence??b.order)),third=Math.floor(ordered.length/3),byId=new Map(rows.map(r=>[r.item.id,r])),first=ordered.slice(0,third).flatMap(i=>byId.has(i.id)?[byId.get(i.id)!]:[]),last=ordered.slice(-third).flatMap(i=>byId.has(i.id)?[byId.get(i.id)!]:[]),acc=config.behavior.acceleration;
  const canAccelerate=sequenceCoverage>=acc.coverage&&third>=acc.minThirdQuestions&&first.length>=acc.minThirdQuestions&&last.length>=acc.minThirdQuestions&&first.length/third>=acc.coverage&&last.length/third>=acc.coverage;
  const accelerationRatio=canAccelerate?median(last.map(r=>r.ratio))!/median(first.map(r=>r.ratio))!:null;
  const acceleration:Component=accelerationRatio===null?missing('Недостаточно последовательности посещений или измерений: нужно минимум 20 вопросов и покрытие 80% в каждой крайней трети'):{score:100*(1-severity(accelerationRatio,acc.warning,acc.critical)),confidence:Math.min(first.length/third,last.length/third),metrics:{acceleration_ratio:accelerationRatio,first_questions:first.length,last_questions:last.length},flags:flag('BEHAVIOR_ACCELERATION','fatigue',accelerationRatio,acc.warning,acc.critical,'Последняя треть пройдена заметно быстрее первой после нормализации по времени отдельных вопросов',config)};
  const expected=rows.reduce((s,r)=>s+r.median,0),observed=rows.reduce((s,r)=>s+Math.min(r.time,Math.max(config.behavior.duration.absoluteCapSeconds,r.median*config.behavior.duration.medianMultiplier)),0),durationRatio=expected>0?observed/expected:null,d=config.behavior.duration;
  const duration:Component=durationRatio===null?missing('Reference median не позволяет оценить активную длительность'):{score:100*(1-severity(durationRatio,d.warning,d.critical)),confidence:coverage*refCoverage,metrics:{duration_ratio:durationRatio,observed_total:observed,expected_total:expected},flags:flag('BEHAVIOR_LOW_ACTIVE_DURATION','speeding',durationRatio,d.warning,d.critical,'Суммарное активное время ответов заметно меньше reference; общее календарное время не используется',config)};
  const available=[pace,bursts,acceleration,duration].filter(c=>c.score!==null).length,sourceConfidence=mean(rows.map(r=>(r.population==='trusted'?1:config.reference.completedConfidence)*(r.source==='question'?1:r.source==='block'?config.reference.blockConfidence:config.reference.typeConfidence)))??config.reference.completedConfidence;
  return index({pace,bursts,acceleration,duration},config.behavior.weights,{...metrics,...pace.metrics,...bursts.metrics,...acceleration.metrics,...duration.metrics},coverage*refCoverage*Math.min(1,rows.length/50)*available/4*sourceConfidence,baseline,config,now);
}
export function response(person:Participant,items:Item[],model:ReferenceModel|null,baseline:Baseline|null,config:QualityConfig,now:string):Index{
  if(person.status!=='completed')return index({rpr:missing('Прохождение ещё не завершено'),pairs:missing('Прохождение ещё не завершено'),patterning:missing('Прохождение ещё не завершено'),attention:missing('Прохождение ещё не завершено')},config.response.weights,{},0,baseline,config,now);
  const eligible=items.filter(i=>i.psychological&&!i.exclude&&i.attentionExpected===undefined),answered=eligible.filter(i=>person.answers[i.id]),keyed=answered.filter(i=>i.scales.length),keysCoverage=answered.length?keyed.length/answered.length:0;
  const rprRaw=model?rpr(person,items,model.splits,config):{value:null,sd:null,min:null,max:null,scales:0,resamples:0},pairRaw=model?pairConsistency(person,items,model.pairs,config):{value:null,pairs:0,available:0};
  const calibration=baseline?Object.entries(baseline.calibrationObservations).filter(([id])=>id!==person.id).map(([,v])=>v):[];
  const rprReference=stats(calibration.flatMap(v=>v.rpr===null?[]:[v.rpr])),pairReference=stats(calibration.flatMap(v=>v.pairs===null?[]:[v.pairs]));
  const calibrate=(value:number|null,reference:ReturnType<typeof stats>)=>calibratedScore(value,reference,config.reference);
  const rrScore=calibrate(rprRaw.value,rprReference),ppScore=calibrate(pairRaw.value,pairReference);
  const rprComponent:Component={score:rrScore,confidence:rrScore===null?0:keysCoverage*Math.min(1,rprRaw.scales/config.response.rpr.confidenceScales)*Math.min(1,calibration.length/config.reference.stableTailN),metrics:{rpr:rprRaw.value,rpr_sd:rprRaw.sd,rpr_min:rprRaw.min,rpr_max:rprRaw.max,scales:rprRaw.scales,resamples:rprRaw.resamples,reference_percentile:lowerTailPercentile(rprRaw.value,rprReference),reference_n:rprReference?.n??0},flags:rrScore!==null&&rrScore<70?[{code:'RESPONSE_LOW_RPR',domain:'response_consistency',severity:rrScore<30?'strong':'warning',value:rprRaw.value,threshold:rprReference!.p05,explanation:'Воспроизводимость профиля по случайным половинам шкал ниже нижнего хвоста reference выборки. Это повод для проверки, не доказательство недостоверности'}]:[],reason:rrScore===null?'Недостаточно шкал, вариативности или калибровочных наблюдений RPR':undefined};
  const pairsComponent:Component={score:ppScore,confidence:ppScore===null?0:keysCoverage*Math.min(1,pairRaw.pairs/config.response.pairs.confidencePairs)*Math.min(1,calibration.length/config.reference.stableTailN),metrics:{pair_consistency:pairRaw.value,pairs:pairRaw.pairs,available_pairs:pairRaw.available,reference_percentile:lowerTailPercentile(pairRaw.value,pairReference),reference_n:pairReference?.n??0},flags:ppScore!==null&&ppScore<70?[{code:'RESPONSE_LOW_PAIR_CONSISTENCY',domain:'response_consistency',severity:ppScore<30?'strong':'warning',value:pairRaw.value,threshold:pairReference!.p05,explanation:'Согласованность эмпирически связанных пунктов ниже reference распределения; для членов baseline использованы пары из других folds'}]:[],reason:ppScore===null?'Недостаточно независимых пар или калибровочных наблюдений':undefined};
  const observedPatterns=patterns(person,items,config),patternFlags:Flag[]=[],patternSeverities:number[]=[],patternDetails:Record<string,unknown>={};
  for(const[block,p]of Object.entries(observedPatterns)){const refs=model?.patterns[block];patternDetails[block]={...p,run_reference:refs?.run??null,entropy_reference:refs?.entropy??null};if(!refs?.run||!refs.entropy||refs.run.n<config.reference.minCalibrationN)continue;const stable=refs.run.n>=config.reference.stableTailN,upper=Math.max(refs.run.p95+1,stable?refs.run.p99:Math.max(refs.run.p99,refs.run.p95*config.response.patterning.conservativeTailMultiplier)),lower=Math.min(refs.entropy.p05-.01,stable?refs.entropy.p01:Math.max(0,refs.entropy.median-config.reference.conservativeMadMultiplier*refs.entropy.mad));const runSeverity=severity(p.run,refs.run.p95,upper),entropySeverity=severity(p.entropy,refs.entropy.p05,lower),combined=Math.max(runSeverity*config.response.patterning.maxPenalty,entropySeverity*config.response.patterning.moderatePenalty)/100;patternSeverities.push(combined);if(p.run>upper)patternFlags.push({code:'RESPONSE_EXTREME_LONGSTRING',severity:'warning',domain:'patterning',value:p.run,threshold:upper,explanation:`${p.title}: серия одинаковых ответов в экстремальном хвосте reference этого блока; сама по себе не доказывает плохое качество`});if(entropySeverity>.85)patternFlags.push({code:'RESPONSE_LOW_ENTROPY',severity:'warning',domain:'patterning',value:p.entropy,threshold:lower,explanation:`${p.title}: разнообразие ответов ниже reference хвоста; крайний психологический профиль может объяснять такой результат`});}
  const patternComponent:Component={score:patternSeverities.length?100*(1-Math.max(...patternSeverities)):null,confidence:patternSeverities.length?Math.min(1,model!.n/config.reference.stableTailN):0,metrics:{blocks:patternDetails},flags:patternFlags,reason:patternSeverities.length?undefined:'Недостаточно baseline для оценки экстремальности серий и entropy'};
  const checks=items.filter(i=>i.attentionExpected!==undefined),respondedChecks=checks.filter(i=>person.answers[i.id]),failed=respondedChecks.filter(i=>String(person.answers[i.id].value)!==String(i.attentionExpected)).length;
  const attention:Component=checks.length&&respondedChecks.length===checks.length?{score:failed===0?100:failed===1?config.response.attention.oneFailedScore:config.response.attention.multipleFailedScore,confidence:1,metrics:{total:checks.length,answered:respondedChecks.length,failed},flags:failed?[{code:'RESPONSE_ATTENTION_CHECK_FAILED',severity:failed>=2?'strong':'warning',domain:'attention',value:failed,threshold:2,explanation:`Не выполнено проверок внимания: ${failed}. Требуется ручная проверка; результаты не удаляются автоматически`}]:[]}:missing('Проверки внимания отсутствуют либо не заполнены');
  let components={rpr:rprComponent,pairs:pairsComponent,patterning:patternComponent,attention};
  if(person.status!=='completed'||answered.length<config.response.minItems||keysCoverage<config.response.minItemCoverage){components={rpr:missing('Недостаточно завершённых ответов с проверенными ключами'),pairs:missing('Недостаточно проверенных ключей'),patterning:patternComponent,attention};}
  const present=Object.entries(components).filter(([,c])=>c.score!==null),weight=present.reduce((s,[k])=>s+config.response.weights[k as keyof typeof config.response.weights],0),confidence=weight?present.reduce((s,[k,c])=>s+c.confidence*config.response.weights[k as keyof typeof config.response.weights],0)/weight:0;
  return index(components,config.response.weights,{answered:answered.length,keyed:keyed.length,key_coverage:keysCoverage,rpr:rprRaw,pair_consistency:pairRaw,patterns:patternDetails,attention_checks_total:checks.length,attention_checks_failed:checks.length?failed:null},confidence*Math.min(1,answered.length/50)*(weight||0),baseline,config,now);
}
export function aggregateOverall(behavior:Index,responses:Index,baseline:Baseline|null,config:QualityConfig,now:string):Index{
  const components:Record<string,Component>={behavioral:{score:behavior.score,confidence:behavior.confidence,metrics:{},flags:behavior.flags},response:{score:responses.score,confidence:responses.confidence,metrics:{},flags:responses.flags}};
  const confidence=behavior.score!==null&&responses.score!==null?Math.min(behavior.confidence,responses.confidence):Math.min(config.overall.partialConfidenceCap,behavior.score!==null?behavior.confidence:responses.confidence);
  const out=index(components,{behavioral:config.overall.behavioral,response:config.overall.response},{basis:behavior.score===null?'response_only':responses.score===null?'behavior_only':'both'},confidence,baseline,config,now);
  if(out.partial)out.flags.push({code:'PARTIAL_QUALITY_RESULT',severity:'info',domain:'data',value:null,threshold:null,explanation:behavior.score===null?'Поведенческая телеметрия отсутствует или недостаточна; итог основан только на доступных данных качества ответов':'Данные качества ответов недостаточны; итог основан только на поведенческих данных'});return out;
}
function hasRequiredAnswer(item:Item,value:unknown){
 if(item.type==='text')return typeof value==='string'&&value.trim().length>0;
 if(item.type==='number')return (typeof value==='number'||typeof value==='string'&&value.trim().length>0)&&Number.isFinite(Number(value));
 if(item.type==='single')return item.options.some(o=>String(o.value)===String(value));
 if(item.type==='multiple')return Array.isArray(value)&&value.length>0&&value.every(v=>item.options.some(o=>String(o.value)===String(v)));
 return value!==null&&value!==undefined;
}
export function calculateV2(person:Participant,items:Item[],baseline:Baseline|null,now=new Date().toISOString()):QualityV2{
  const config=baseline?.config??QUALITY_V2_CONFIG,model=baseline?(baseline.memberFold[person.id]!==undefined?baseline.folds[baseline.memberFold[person.id]]:baseline.full):null;
  const behavior=behavioral(person,items,model,baseline,config,now),responses=response(person,items,model,baseline,config,now),overall=aggregateOverall(behavior,responses,baseline,config,now),flags=overall.flags;
  const required=items.filter(i=>i.required),answered=required.filter(i=>hasRequiredAnswer(i,person.answers[i.id]?.value));
  return{version:2,algorithm_version:config.version,config_hash:baseline?.configHash??hash(config),baseline_version:baseline?.version??null,calculated_at:now,overall,behavioral:behavior,response:responses,strong_flag_count:flags.filter(f=>f.severity==='strong').length,warning_flag_count:flags.filter(f=>f.severity==='warning').length,independent_concerning_domains:new Set(flags.filter(f=>f.severity==='strong').map(f=>f.domain)).size,hard_checks:{eligibility:person.eligibility,eligibility_reason:person.eligibilityReason,duplicate:person.duplicate,completeness:{required:required.length,answered:answered.length,complete:answered.length===required.length}},cohort:person.cohort,telemetry_version:person.telemetryVersion,input_hash:hash({items,person:{...person,legacy_quality_v1:undefined}})};
}
