import { normalized } from './keys.js';
import { mean, median, mad, sd, spearman, shuffled, stats } from './math.js';
import type { Item, Participant, Pair, Split, ReferenceModel, ReferenceStats } from './types.js';
import type { QualityConfig } from './config.js';

export function scaleGroups(items:Item[]){const out=new Map<string,Item[]>();for(const item of items)if(item.psychological&&!item.exclude&&item.attentionExpected===undefined)for(const scale of item.scales){const a=out.get(scale.id)??[];a.push(item);out.set(scale.id,a)}return out;}
export function scaleMean(person:Participant,items:Item[],scale:string,coverage=1){const values=items.flatMap(item=>{const v=normalized(item,person.answers[item.id]?.value,scale);return v===null?[]:[v]});return values.length>=Math.ceil(items.length*coverage)?mean(values):null;}
export function buildSplits(items:Item[],people:Participant[],config:QualityConfig,seed:string):Split[][]{
  const scales=[...scaleGroups(items)].filter(([,a])=>a.length>=config.response.rpr.minItemsPerScale);
  return Array.from({length:config.response.rpr.resamples},(_,sample)=>scales.flatMap(([scale,questions])=>{
    const ordered=shuffled(questions,`${seed}:${scale}:${sample}`),a=ordered.slice(0,Math.ceil(ordered.length/2)),b=ordered.slice(a.length);
    const av=people.flatMap(p=>{const v=scaleMean(p,a,scale,config.response.rpr.halfCoverage);return v===null?[]:[v]}),bv=people.flatMap(p=>{const v=scaleMean(p,b,scale,config.response.rpr.halfCoverage);return v===null?[]:[v]});
    if(av.length<config.reference.minQuestionN||bv.length<config.reference.minQuestionN)return[];
    const spreadA=mad(av)*1.4826||sd(av)||0,spreadB=mad(bv)*1.4826||sd(bv)||0;if(!spreadA||!spreadB)return[];
    return[{scale,a:a.map(x=>x.id),b:b.map(x=>x.id),centerA:median(av)!,spreadA,centerB:median(bv)!,spreadB}];
  }));
}
export function rpr(person:Participant,items:Item[],splits:Split[][],config:QualityConfig){
  const lookup=new Map(items.map(item=>[item.id,item])),correlations:number[]=[],counts:number[]=[];
  for(const sample of splits){const a:number[]=[],b:number[]=[],rawA:number[]=[],rawB:number[]=[];for(const split of sample){const va=scaleMean(person,split.a.map(id=>lookup.get(id)!),split.scale,config.response.rpr.halfCoverage),vb=scaleMean(person,split.b.map(id=>lookup.get(id)!),split.scale,config.response.rpr.halfCoverage);if(va===null||vb===null)continue;rawA.push(va);rawB.push(vb);a.push((va-split.centerA)/split.spreadA);b.push((vb-split.centerB)/split.spreadB)}if(a.length<config.response.rpr.minScales||(sd(rawA)??0)<1e-12||(sd(rawB)??0)<1e-12)continue;const correlation=spearman(a,b);if(correlation!==null){correlations.push(correlation);counts.push(a.length)}}
  if(correlations.length<config.response.rpr.minValidResamples)return{value:null,sd:null,min:null,max:null,scales:counts.length?Math.min(...counts):0,resamples:correlations.length};
  const clip=config.response.rpr.clip,value=Math.tanh(mean(correlations.map(r=>Math.atanh(Math.max(-clip,Math.min(clip,r)))))!);
  return{value,sd:sd(correlations),min:Math.min(...correlations),max:Math.max(...correlations),scales:Math.min(...counts),resamples:correlations.length};
}
export function buildPairs(items:Item[],people:Participant[],config:QualityConfig):Pair[]{
  const eligible=items.filter(item=>item.scales.length&&item.attentionExpected===undefined&&!item.exclude),vectors=new Map(eligible.map(item=>[item.id,people.map(p=>normalized(item,p.answers[item.id]?.value))]));const candidates:Pair[]=[];
  for(let i=0;i<eligible.length;i++)for(let j=i+1;j<eligible.length;j++){const x=vectors.get(eligible[i].id)!,y=vectors.get(eligible[j].id)!,a:number[]=[],b:number[]=[];for(let k=0;k<x.length;k++)if(x[k]!==null&&y[k]!==null){a.push(x[k]!);b.push(y[k]!)}if(a.length<config.response.pairs.minN)continue;const rho=spearman(a,b);if(rho!==null&&Math.abs(rho)>=config.response.pairs.rho)candidates.push({a:eligible[i].id,b:eligible[j].id,rho,n:a.length})}
  candidates.sort((a,b)=>Math.abs(b.rho)-Math.abs(a.rho)||a.a.localeCompare(b.a)||a.b.localeCompare(b.b));const used=new Map<string,number>(),selected:Pair[]=[];
  for(const pair of candidates){if((used.get(pair.a)??0)>=config.response.pairs.maxPerItem||(used.get(pair.b)??0)>=config.response.pairs.maxPerItem)continue;selected.push(pair);used.set(pair.a,(used.get(pair.a)??0)+1);used.set(pair.b,(used.get(pair.b)??0)+1)}return selected;
}
export function pairConsistency(person:Participant,items:Item[],pairs:Pair[],config:QualityConfig){const lookup=new Map(items.map(item=>[item.id,item]));let total=0,weight=0,count=0;for(const pair of pairs){const a=normalized(lookup.get(pair.a)!,person.answers[pair.a]?.value),b=normalized(lookup.get(pair.b)!,person.answers[pair.b]?.value);if(a===null||b===null)continue;total+=(1-Math.abs(a-(pair.rho<0?1-b:b)))*Math.abs(pair.rho);weight+=Math.abs(pair.rho);count++}return{value:count>=config.response.pairs.minPairs&&weight>0?total/weight:null,pairs:count,available:pairs.length};}
export function patterns(person:Participant,items:Item[],config:QualityConfig){const blocks=new Map<string,Item[]>();for(const item of items)if(item.psychological&&!item.exclude&&item.attentionExpected===undefined&&item.type==='single'&&item.options.length>=2){const a=blocks.get(item.block)??[];a.push(item);blocks.set(item.block,a)}const out:Record<string,{run:number;entropy:number;answered:number;categories:number;title:string}>={};
  for(const[block,questions]of blocks){questions.sort((a,b)=>a.position-b.position);let run=0,longest=0,previous:string|undefined,position:number|undefined,signature='';const segments=new Map<string,{counts:Map<string,number>;n:number;categories:number}>();for(const item of questions){const raw=person.answers[item.id]?.value,valid=(typeof raw==='number'||typeof raw==='string')&&item.options.some(option=>String(option.value)===String(raw)),scale=JSON.stringify(item.options);if(!valid){run=0;previous=undefined;position=item.position;continue}const value=String(raw);run=position!==undefined&&item.position===position+1&&signature===scale&&previous===value?run+1:1;longest=Math.max(longest,run);previous=value;position=item.position;signature=scale;const segment=segments.get(scale)??{counts:new Map(),n:0,categories:item.options.length};segment.counts.set(value,(segment.counts.get(value)??0)+1);segment.n++;segments.set(scale,segment)}let total=0,entropy=0,categories=0;for(const segment of segments.values()){if(segment.n<config.response.patterning.minBlockItems)continue;const h=-[...segment.counts.values()].reduce((s,n)=>{const p=n/segment.n;return s+p*Math.log(p)},0)/Math.log(segment.categories);entropy+=h*segment.n;total+=segment.n;categories=Math.max(categories,segment.categories)}if(total>=config.response.patterning.minBlockItems)out[block]={run:longest,entropy:entropy/total,answered:total,categories,title:questions[0].title};}return out;
}
export function referenceModel(items:Item[],people:Participant[],config:QualityConfig,seed:string,includePsychometrics=true):ReferenceModel{
  const time:ReferenceModel['time']={},blockTime:ReferenceModel['blockTime']={},typeTime:ReferenceModel['typeTime']={};
  const eligible=items.filter(i=>i.psychological&&!i.exclude&&i.attentionExpected===undefined);
  for(const item of eligible){const observations=people.flatMap(p=>{const v=p.answers[item.id]?.activeSeconds;return v!=null&&Number.isFinite(v)&&v>=0?[v]:[]}),ref=stats(observations);if(ref){ref.mad=mad(observations.map(t=>Math.log(t+config.behavior.offsetSeconds)));time[item.id]=ref}}
  for(const[group,field]of [['block','blockTime'],['type','typeTime']] as const){for(const key of new Set(eligible.map(i=>i[group]))){const observations=people.flatMap(p=>{const values=eligible.filter(i=>i[group]===key).flatMap(i=>{const t=p.answers[i.id]?.activeSeconds;return t!=null&&Number.isFinite(t)&&t>=0?[t]:[]});return values.length?[median(values)!]:[]}),ref=stats(observations);if(ref){ref.mad=mad(observations.map(t=>Math.log(t+config.behavior.offsetSeconds)));(field==='blockTime'?blockTime:typeTime)[key]=ref}}}
  const distributions:Record<string,{runs:number[];entropies:number[]}>={};for(const person of people)for(const[key,p]of Object.entries(patterns(person,items,config))){const d=distributions[key]??{runs:[],entropies:[]};d.runs.push(p.run);d.entropies.push(p.entropy);distributions[key]=d}
  return{n:people.length,time,blockTime,typeTime,pairs:includePsychometrics?buildPairs(items,people,config):[],splits:includePsychometrics?buildSplits(items,people,config,seed):[],patterns:Object.fromEntries(Object.entries(distributions).map(([key,d])=>[key,{run:stats(d.runs),entropy:stats(d.entropies)}]))};
}
export function lowerTailPercentile(value:number|null,reference:ReferenceStats|null){if(value===null||!reference)return null;const knots=[[reference.p01,.01],[reference.p05,.05],[reference.p10,.1],[reference.p25,.25],[reference.median,.5],[reference.p75,.75],[reference.p90,.9],[reference.p95,.95],[reference.p99,.99]];if(value<knots[0][0])return 0;for(let i=1;i<knots.length;i++)if(value<=knots[i][0])return knots[i-1][1]+(knots[i][1]-knots[i-1][1])*(value-knots[i-1][0])/Math.max(1e-12,knots[i][0]-knots[i-1][0]);return 1;}
