import { Router } from 'express';
import { z } from 'zod';
import { db } from '../db.js';
import { requireAuth, type AuthRequest } from '../auth.js';
import { activeBaseline, enqueueQuality, json, qualityEnabled, storedQualities } from './service.js';
import { QUALITY_V2_CONFIG } from './config.js';
export const qualityRouter=Router();
qualityRouter.use('/admin/surveys/:id/quality-v2',requireAuth,async(req:AuthRequest,res,next)=>{try{const[allowed]=await db.query<any[]>('SELECT id FROM surveys WHERE id=? AND owner_id=?',[req.params.id,req.user!.id]);if(!allowed.length)return res.status(404).json({message:'Опрос не найден'});next()}catch(error){next(error)}});
qualityRouter.get('/admin/surveys/:id/quality-v2',async(req,res,next)=>{try{const id=String(req.params.id),baseline=await activeBaseline(id);const[versions]=await db.query<any[]>('SELECT id,algorithm_version algorithmVersion,created_at createdAt FROM quality_baselines WHERE survey_id=? ORDER BY created_at DESC',[id]);const[jobs]=await db.query<any[]>('SELECT id,kind,status,progress,total,error,created_at createdAt FROM quality_jobs WHERE survey_id=? ORDER BY created_at DESC LIMIT 5',[id]);res.json({enabled:qualityEnabled(),algorithm_version:QUALITY_V2_CONFIG.version,baseline:baseline?{version:baseline.version,source:baseline.source,n:baseline.memberIds.length,created_at:baseline.createdAt,config_hash:baseline.configHash,time_questions:Object.values(baseline.full.time).filter(s=>s.n>=baseline.config.reference.minQuestionN).length,pairs:baseline.full.pairs.length,calibration:baseline.calibration}:null,versions,jobs})}catch(error){next(error)}});
qualityRouter.post('/admin/surveys/:id/quality-v2/baseline',async(req,res,next)=>{try{const options=z.object({cohort:z.string().max(100).optional()}).parse(req.body);const job=await enqueueQuality(String(req.params.id),'baseline',options);if(!job)return res.status(409).json({message:'Quality V2 отключена конфигурацией сервера'});res.status(202).json({jobId:job})}catch(error){next(error)}});
qualityRouter.post('/admin/surveys/:id/quality-v2/recompute',async(req,res,next)=>{try{const options=z.object({sessionId:z.string().uuid().optional(),cohort:z.string().max(100).optional(),baselineVersion:z.string().max(64).optional()}).parse(req.body);const job=await enqueueQuality(String(req.params.id),'recompute',options);if(!job)return res.status(409).json({message:'Quality V2 отключена конфигурацией сервера'});res.status(202).json({jobId:job})}catch(error){next(error)}});
qualityRouter.post('/admin/surveys/:id/quality-v2/metadata',async(req,res,next)=>{try{const body=z.object({sessionIds:z.array(z.string().uuid()).min(1).max(1000),cohort:z.enum(['unassigned','trusted','public','admin_test']).optional(),trusted:z.boolean().optional(),eligibility:z.enum(['unknown','pass','fail']).optional(),eligibilityReason:z.string().max(1000).nullable().optional(),duplicate:z.boolean().optional(),telemetryVersion:z.string().max(60).nullable().optional()}).parse(req.body);const connection=await db.getConnection();try{await connection.beginTransaction();for(const sessionId of body.sessionIds){const[rows]=await connection.query<any[]>('SELECT id FROM response_sessions WHERE id=? AND survey_id=?',[sessionId,req.params.id]);if(!rows.length)throw Object.assign(new Error('Прохождение не принадлежит опросу'),{status:400});await connection.execute('INSERT IGNORE INTO quality_metadata(session_id) VALUES (?)',[sessionId]);const assignments:string[]=[],values:any[]=[];for(const[property,column]of Object.entries({cohort:'cohort',trusted:'calibration_trusted',eligibility:'eligibility',eligibilityReason:'eligibility_reason',duplicate:'confirmed_duplicate',telemetryVersion:'telemetry_version'})){const value=body[property as keyof typeof body];if(value!==undefined){assignments.push(`${column}=?`);values.push(value)}}if(assignments.length)await connection.execute(`UPDATE quality_metadata SET ${assignments.join(',')} WHERE session_id=?`,[...values,sessionId]);}await connection.commit()}catch(error){await connection.rollback();throw error}finally{connection.release()}const job=await enqueueQuality(String(req.params.id),'recompute',{});res.json({updated:body.sessionIds.length,jobId:job})}catch(error){next(error)}});
qualityRouter.get('/admin/surveys/:id/quality-v2/jobs/:jobId',async(req,res,next)=>{try{const[rows]=await db.query<any[]>('SELECT id,kind,status,progress,total,error,output FROM quality_jobs WHERE id=? AND survey_id=?',[req.params.jobId,req.params.id]);if(!rows.length)return res.status(404).json({message:'Задание не найдено'});res.json({...rows[0],output:json(rows[0].output)})}catch(error){next(error)}});
qualityRouter.get('/admin/surveys/:id/quality-v2/diagnostics',async(req,res,next)=>{try{const baseline=await activeBaseline(String(req.params.id)),[rows]=await db.query<any[]>("SELECT output FROM quality_jobs WHERE survey_id=? AND kind='recompute' AND status='completed' ORDER BY updated_at DESC LIMIT 20",[req.params.id]);const output=rows.map(row=>json(row.output)).find(value=>value?.diagnostics&&value?.baseline_version===(baseline?.version??null));res.json(output?.diagnostics??null)}catch(error){next(error)}});
qualityRouter.get('/admin/surveys/:id/quality-v2/results',async(req,res,next)=>{try{res.json(qualityEnabled()?await storedQualities(String(req.params.id)):{})}catch(error){next(error)}});

qualityRouter.post('/admin/surveys/:id/quality-v2/retry',async(req,res,next)=>{try{const {jobId}=z.object({jobId:z.string().uuid()}).parse(req.body);const [rows]=await db.query<any[]>("SELECT kind,options FROM quality_jobs WHERE id=? AND survey_id=? AND status='failed'",[jobId,req.params.id]);if(!rows.length)return res.status(404).json({message:'Ошибочное задание не найдено'});const id=await enqueueQuality(String(req.params.id),rows[0].kind,json(rows[0].options));res.status(202).json({jobId:id})}catch(error){next(error)}});

qualityRouter.post('/admin/surveys/:id/quality-v2/activate',async(req,res,next)=>{try{const {baselineVersion}=z.object({baselineVersion:z.string().max(64)}).parse(req.body);const [rows]=await db.query<any[]>('SELECT id FROM quality_baselines WHERE id=? AND survey_id=? AND algorithm_version=?',[baselineVersion,req.params.id,QUALITY_V2_CONFIG.version]);if(!rows.length)return res.status(404).json({message:'Версия baseline не найдена'});await db.execute('INSERT INTO quality_settings(survey_id,active_baseline) VALUES (?,?) ON DUPLICATE KEY UPDATE active_baseline=VALUES(active_baseline)',[req.params.id,baselineVersion]);const id=await enqueueQuality(String(req.params.id),'recompute',{baselineVersion});res.status(202).json({jobId:id})}catch(error){next(error)}});
qualityRouter.get('/admin/surveys/:id/quality-v2/snapshot/:sessionId',async(req,res,next)=>{try{const b=await activeBaseline(String(req.params.id));if(!b)return res.status(404).json({message:'Нет активной baseline'});const [rows]=await db.query<any[]>('SELECT r.input_snapshot,r.result FROM quality_results r JOIN quality_result_heads h ON h.session_id=r.session_id AND h.algorithm_version=r.algorithm_version AND h.baseline_version=r.baseline_version AND h.input_hash=r.input_hash JOIN response_sessions s ON s.id=r.session_id WHERE s.survey_id=? AND r.session_id=? AND r.baseline_version=? AND r.algorithm_version=?',[req.params.id,req.params.sessionId,b.version,b.config.version]);if(!rows.length)return res.status(404).json({message:'Сохранённый результат не найден'});const original=json(rows[0].result);res.json({...json(rows[0].input_snapshot),baseline:b,calculated_at:original.calculated_at,expected_result:original})}catch(error){next(error)}});
