import{describe,expect,it}from'vitest';
import{bfi2Instrument}from'../data/bfi2.js';
import{BFI2_REVERSE_ITEMS,scoreBfi2}from'./bfi2.js';
const answers=(value:number)=>new Map(Array.from({length:60},(_,index)=>[index+1,value]));
describe('scoreBfi2',()=>{
  it('ships the official 60-item Russian form and response scale',()=>{expect(bfi2Instrument.questions).toHaveLength(60);expect(bfi2Instrument.questions.map(q=>q.code)).toEqual(Array.from({length:60},(_,i)=>`test_12_${i+1}`));expect(bfi2Instrument.questions.every(q=>q.options?.map(o=>o.value).join(',')==='1,2,3,4,5')).toBe(true)});
  it('contains the complete official reverse key',()=>expect(BFI2_REVERSE_ITEMS).toEqual([3,4,5,8,9,11,12,16,17,22,23,24,25,26,28,29,30,31,36,37,42,44,45,47,48,49,50,51,55,58]));
  it('applies the direction of every item in the actual domain scorer',()=>{const reverse=new Set<number>(BFI2_REVERSE_ITEMS);const baseline=scoreBfi2(answers(3))!;const baselineTotal=Object.values(baseline.domains).reduce((sum,x)=>sum+x.score,0);for(let item=1;item<=60;item++){const input=answers(3);input.set(item,4);const total=Object.values(scoreBfi2(input)!.domains).reduce((sum,x)=>sum+x.score,0);expect(total-baselineTotal,`item ${item}`).toBe(reverse.has(item)?-1:1)}});
  it('calculates theoretical minima and maxima',()=>{const min=answers(1);BFI2_REVERSE_ITEMS.forEach(i=>min.set(i,5));const minResult=scoreBfi2(min)!;expect(Object.values(minResult.domains).every(x=>x.average===1)).toBe(true);expect(Object.values(minResult.facets).every(x=>x.average===1)).toBe(true);const max=answers(5);BFI2_REVERSE_ITEMS.forEach(i=>max.set(i,1));const maxResult=scoreBfi2(max)!;expect(Object.values(maxResult.domains).every(x=>x.average===5)).toBe(true);expect(Object.values(maxResult.facets).every(x=>x.average===5)).toBe(true)});
  it('calculates a mixed protocol and facets independently',()=>{const input=answers(3);input.set(1,5);input.set(16,5);const result=scoreBfi2(input)!;expect(result.facets.sociability).toMatchObject({score:12,average:3});expect(result.domains.extraversion).toMatchObject({score:36,average:3});expect(result.domains.agreeableness.average).toBe(3)});
  it('rejects incomplete, invalid, and wrong-key protocols',()=>{const incomplete=answers(3);incomplete.delete(60);expect(scoreBfi2(incomplete)).toBeNull();const invalid=answers(3);invalid.set(60,6);expect(scoreBfi2(invalid)).toBeNull();const wrong=answers(3);wrong.delete(1);wrong.set(61,3);expect(scoreBfi2(wrong)).toBeNull()});
});
