export type Methodology={code:string;title:string;version:string;summary:string;steps:string[];keys?:{label:string;value:string}[];norms?:{label:string;value:string}[];notes:string[];sources:{title:string;url:string}[]};

export const methodologies:Record<string,Methodology>={
  test_1:{
    code:'test_1',title:'Многомерная шкала восприятия социальной поддержки, MSPSS',version:'mspss-zimet-v1',
    summary:'MSPSS измеряет субъективно воспринимаемую поддержку из трёх источников: семьи, друзей и значимого другого. Обратных пунктов нет; чем выше средний балл, тем выше воспринимаемая поддержка.',
    steps:['Все ответы используются в исходном виде по шкале от 1 до 7.','Для каждой субшкалы складываются четыре относящихся к ней ответа, затем сумма делится на 4.','Общий показатель — сумма всех 12 ответов, делённая на 12.','Результат формируется только при наличии всех 12 ответов.'],
    keys:[{label:'Значимый другой',value:'Пункты 1, 2, 5, 10. Формула: (Q1 + Q2 + Q5 + Q10) / 4.'},{label:'Семья',value:'Пункты 3, 4, 8, 11. Формула: (Q3 + Q4 + Q8 + Q11) / 4.'},{label:'Друзья',value:'Пункты 6, 7, 9, 12. Формула: (Q6 + Q7 + Q9 + Q12) / 4.'},{label:'Общий показатель',value:'Среднее всех 12 пунктов; диапазон 1–7.'}],
    norms:[{label:'Ориентировочная группировка автора',value:'Низкая поддержка: <3; умеренная: 3–5; высокая: >5.'}],
    notes:['Для MSPSS нет универсальных популяционных норм: показатели могут зависеть от культуры, страны, возраста и пола. Уровни являются ориентировочной группировкой по смыслу семибалльной шкалы, а не клиническими порогами.','Альтернативное деление конкретной выборки на три равные группы не используется, чтобы результат респондента не менялся при добавлении новых анкет.'],
    sources:[{title:'Официальная страница ресурсов MSPSS Грегори Зимета',url:'https://gzimet.wixsite.com/mspss/about-us'},{title:'Авторская инструкция по подсчёту MSPSS',url:'https://www.researchgate.net/publication/311534896_Multidimensional_Scale_of_Perceived_Social_Support_MSPSS_-_Scale_Items_and_Scoring_Information'},{title:'Zimet et al. — оригинальная публикация MSPSS (1988)',url:'https://doi.org/10.1207/s15327752jpa5201_2'},{title:'Описание русскоязычной версии MSPSS',url:'https://psytests.org/coping/mspss-run.html'}]
  },
  test_4:{
    code:'test_4',title:'Шкала негативного образа себя, NSPS',version:'nsps-moscovitch-huyder-v1',
    summary:'NSPS оценивает обеспокоенность тем, что окружающим станут заметны воспринимаемые недостатки в социальной компетентности, внешности или признаки тревоги. Чем выше сумма, тем сильнее соответствующая обеспокоенность.',
    steps:['Все 27 ответов используются напрямую по шкале от 1 до 5; обратных пунктов нет.','Баллы отдельно суммируются по трём субшкалам.','Общий показатель равен сумме всех 27 ответов и находится в диапазоне 27–135.','Результат формируется только после ответа на все 27 пунктов.'],
    keys:[{label:'Социальная компетентность',value:'Пункты 3, 10, 12, 14, 17, 18, 19, 20, 21, 23, 24. Диапазон 11–55.'},{label:'Физическая внешность',value:'Пункты 2, 5, 9, 11, 13, 22, 26, 27. Диапазон 8–40.'},{label:'Признаки тревоги',value:'Пункты 1, 4, 6, 7, 8, 15, 16, 25. Диапазон 8–40.'},{label:'Общий показатель',value:'Сумма пунктов 1–27. Диапазон 27–135.'}],
    norms:[{label:'Справочные данные клинического исследования, N=194',value:'Здоровый контроль: общий M=47,0 (SD=25,3); социальная компетентность 19,4 (7,6); внешность 14,4 (6,7); признаки тревоги 13,8 (5,5). Эти значения не являются диагностическими порогами.'}],
    notes:['У NSPS нет универсальных валидированных границ «низкий / средний / высокий», поэтому система показывает сырые суммы и не присваивает диагностическую категорию.','Русский текст в анкете является переводом psytests.org 2024 года; на странице перевода прямо указано, что сведений о русскоязычной психометрической адаптации нет. Результаты следует интерпретировать с этой оговоркой.','Три субшкалы содержат разное число пунктов, поэтому их сырые суммы нельзя напрямую сравнивать между собой как равные шкалы. Визуализация учитывает собственный диапазон каждой субшкалы.'],
    sources:[{title:'Moscovitch & Huyder — оригинальная публикация NSPS (2011)',url:'https://doi.org/10.1016/j.beth.2010.04.007'},{title:'Оригинальный бланк NSPS с ключом и справочными данными',url:'https://www.goodmedicine.org.uk/media/files/social%20anxiety%2C%20assessment%20nsps.pdf'},{title:'PubMed — описание трёхфакторной структуры NSPS',url:'https://pubmed.ncbi.nlm.nih.gov/21496505/'},{title:'Описание использованного русского перевода',url:'https://psytests.org/anxiety/nsps.html'}]
  },
  test_5:{code:'test_5',title:'Шкала оценки пищевого поведения, ШОПП',version:'shopp-ru-2011-v1',summary:'Русскоязычная 51-пунктовая версия EDI оценивается по семи самостоятельным субшкалам. Высокий балл означает большую выраженность соответствующего признака; общий суммарный показатель методикой не предусмотрен.',steps:['Ответы «всегда», «обычно», «часто» прямого пункта дают соответственно 3, 2 и 1 балл; остальные — 0.','Для обратного пункта 3, 2 и 1 балл дают соответственно ответы «никогда», «редко», «иногда»; остальные — 0.','Баллы суммируются отдельно внутри каждой из семи субшкал. Результат рассчитывается после всех 51 ответов.'],keys:[{label:'Стремление к худобе',value:'Прямые: 8, 12, 18, 25, 41. Обратный: 1.'},{label:'Булимия',value:'Прямые: 3, 4, 21, 30, 37, 48, 51.'},{label:'Неудовлетворённость телом',value:'Прямые: 2, 6, 36, 46. Обратные: 9, 14, 24, 43, 49.'},{label:'Неэффективность',value:'Прямые: 7, 20, 32, 44. Обратные: 15, 29, 33.'},{label:'Перфекционизм',value:'Прямые: 10, 22, 28, 34, 40, 50.'},{label:'Недоверие в межличностных отношениях',value:'Прямые: 27, 42. Обратные: 11, 13, 17, 23, 45.'},{label:'Интероцептивная некомпетентность',value:'Прямые: 5, 16, 26, 31, 35, 38, 39, 47. Обратный: 19.'}],notes:['Пункты 45 и 49 в опубликованном ключе адаптации содержат ошибку знака. Здесь они отнесены к обратным согласно исправлению источника и смыслу утверждений.','ШОПП является скрининговым и исследовательским инструментом и сама по себе не устанавливает диагноз. Категории «низкий/средний/высокий» не выводятся.'],sources:[{title:'Ильчик и др. — русскоязычная адаптация ШОПП (2011)',url:'https://start.rucont.ru/efd/497449'},{title:'Описание и исправление знаков пунктов 45 и 49',url:'https://psytests.org/diag/edi.html'},{title:'Garner, Olmstead, Polivy — разработка EDI',url:'https://doi.org/10.1002/1098-108X(198321)2:2%3C15::AID-EAT2260020203%3E3.0.CO;2-6'}]},
  test_6:{code:'test_6',title:'Голландский опросник пищевого поведения, DEBQ',version:'debq-van-strien-v2',summary:'DEBQ формирует три независимых средних показателя пищевого поведения: ограничительного, эмоциогенного и экстернального. Результат сравнивается со справочным средним для людей с нормальной массой тела; превышение отмечается как повышенная выраженность соответствующего типа.',steps:['Ответам «никогда» — «очень часто» соответствуют баллы 1–5.','Пункт 31 имеет обратное направление и пересчитывается по формуле 6 − ответ.','По каждой шкале вычисляется среднее арифметическое её пунктов; диапазон каждого результата 1–5.','Полученное среднее сравнивается с ориентиром своей шкалы. Только значение строго выше ориентира отмечается как повышенная выраженность. Равное значение не считается превышением.','Результат рассчитывается после всех 33 ответов.'],keys:[{label:'Ограничительное',value:'Пункты 1–10; среднее 10 пунктов. Нормативный ориентир — 2,4.'},{label:'Эмоциогенное',value:'Пункты 11–23; среднее 13 пунктов. Нормативный ориентир — 1,8.'},{label:'Экстернальное',value:'Пункты 24–33; среднее 10 пунктов. Пункт 31 обратный. Нормативный ориентир — 2,7.'}],norms:[{label:'Ограничительное пищевое поведение',value:'Ориентир 2,4; значение >2,4 — повышенная выраженность.'},{label:'Эмоциогенное пищевое поведение',value:'Ориентир 1,8; значение >1,8 — повышенная выраженность.'},{label:'Экстернальное пищевое поведение',value:'Ориентир 2,7; значение >2,7 — повышенная выраженность.'}],notes:['Шкалы DEBQ самостоятельны: общий балл по всем 33 пунктам не рассчитывается.','Значения 2,4 / 1,8 / 2,7 являются нормативными средними и ориентирами для интерпретации, а не самостоятельными клиническими диагностическими порогами. Повышение требует содержательной оценки специалистом.'],sources:[{title:'DEBQ — описание, обработка и интерпретация',url:'https://psytests.org/diag/debq.html'},{title:'Исследование с нормативами 2,4 / 1,8 / 2,7',url:'https://www.mediasphera.ru/issues/profilakticheskaya-meditsina/2017/6/1230549482017061046'},{title:'van Strien et al. — оригинальная разработка DEBQ (1986)',url:'https://doi.org/10.1002/1098-108X(198602)5:2%3C295::AID-EAT2260050209%3E3.0.CO;2-T'},{title:'Wageningen University — библиографическая запись первоисточника',url:'https://research.wur.nl/en/publications/the-dutch-eating-behavior-questionnaire-debq-for-assessment-of-re/'}]},
  test_2:{
    code:'test_2',title:'Стиль саморегуляции поведения, ССПМ-2011',version:'sspm-2011-v1',
    summary:'За каждое совпадение ответа с ключом начисляется 1 балл. Варианты «Верно» и «Пожалуй, верно» относятся к «Да», варианты «Пожалуй, неверно» и «Неверно» — к «Нет».',
    steps:['Ответы преобразуются в две группы: 1–2 = «Да», 3–4 = «Нет».','Для каждой шкалы отдельно подсчитывается число совпадений с ключом. Максимум по частной шкале — 9 баллов.','Общий уровень считается по самостоятельному ключу из всех 52 пунктов; он не равен простой сумме частных шкал.','Результат формируется только при наличии всех 52 ответов.'],
    keys:[
      {label:'Планирование',value:'Да: 1, 10, 21, 24, 27, 34, 42. Нет: 19, 48.'},{label:'Моделирование',value:'Да: 14, 43. Нет: 4, 5, 8, 23, 28, 31, 39.'},{label:'Программирование',value:'Да: 17, 26, 44, 47, 49. Нет: 3, 7, 11, 36.'},{label:'Оценивание результатов',value:'Да: 16. Нет: 9, 12, 13, 29, 32, 40, 45, 50.'},{label:'Гибкость',value:'Да: 2, 14, 30, 41, 42, 47, 51. Нет: 22, 28.'},{label:'Самостоятельность',value:'Да: 6, 15, 18, 25, 33, 37, 46, 52. Нет: 40.'},{label:'Надёжность',value:'Да: 38. Нет: 3, 5, 8, 12, 20, 29, 35, 36.'},{label:'Общий уровень',value:'Да: 1, 2, 6, 10, 14, 15, 16, 17, 18, 21, 24, 25, 26, 27, 30, 33, 34, 37, 38, 41, 42, 43, 44, 46, 47, 49, 51, 52. Нет: 3, 4, 5, 7, 8, 9, 11, 12, 13, 19, 20, 22, 23, 28, 29, 31, 32, 35, 36, 39, 40, 45, 48, 50.'}
    ],
    norms:[{label:'Планирование, моделирование, оценивание, самостоятельность, надёжность',value:'Низкий: ≤3; средний: 4–6; высокий: ≥7.'},{label:'Программирование, гибкость',value:'Низкий: ≤4; средний: 5–7; высокий: ≥8.'},{label:'Общий уровень',value:'Низкий: ≤25; средний: 26–36; высокий: ≥37.'}],
    notes:['Шкала надёжности относится именно к версии ССПМ-2011 из 52 пунктов. Ключи старой 46-пунктовой версии к этой анкете неприменимы.'],
    sources:[{title:'Описание ССПМ-2011 и библиография первоисточника',url:'https://psytests.org/emvol/sspm11.html'},{title:'Моросанова В. И., Кондратюк Н. Г. Новая версия опросника ССПМ (2011)',url:'https://lib.mgppu.ru/OpacUnicode/index.php?url=%2Fnotices%2Findex%2FIdNotice%3A90946%2FSource%3Adefault'}]
  },
  test_3:{
    code:'test_3',title:'Шкала ясности Я-концепции, SCCS',version:'sccs-ru-2021-v1',
    summary:'SCCS — однофакторная шкала. Основной показатель русскоязычной адаптации — среднее значение 12 ответов после реверсирования десяти обратных пунктов.',
    steps:['Прямые пункты 6 и 11 сохраняют исходный балл.','Обратные пункты 1, 2, 3, 4, 5, 7, 8, 9, 10 и 12 пересчитываются по формуле: 6 − исходный ответ.','Скорректированные баллы складываются. Сумма находится в диапазоне 12–60.','Основной показатель вычисляется как сумма / 12 и находится в диапазоне 1,00–5,00. Чем выше значение, тем выше ясность Я-концепции.','Результат формируется только при наличии всех 12 ответов.'],
    keys:[{label:'Прямые пункты',value:'6, 11.'},{label:'Обратные пункты',value:'1, 2, 3, 4, 5, 7, 8, 9, 10, 12.'},{label:'Реверсивная шкала',value:'1→5, 2→4, 3→3, 4→2, 5→1.'}],
    norms:[{label:'Русскоязычная адаптационная выборка, N=349',value:'M=3,09; SD=0,72; медиана=3,00; наблюдавшийся диапазон 1,80–5,00.'}],
    notes:['Авторы русскоязычной адаптации не устанавливают официальные пороги «низкий / средний / высокий». Поэтому результат выводится как непрерывный показатель без диагностической категоризации.','Положение относительно M и SD адаптационной выборки является справочным и не заменяет клиническую интерпретацию.'],
    sources:[{title:'Вдовенко, Щебетенко, Старовойтенко — русскоязычная адаптация SCCS (2021)',url:'https://psystudy.ru/num/article/download/157/97/102'},{title:'Campbell et al. — оригинальная публикация SCCS (1996)',url:'https://doi.org/10.1037/0022-3514.70.1.141'},{title:'Описание используемой русскоязычной версии SCCS',url:'https://psytests.org/ident/sccs.html'}]
  },
  test_7:{
    code:'test_7',title:'Шкала академической мотивации, ШАМ',version:'sham-gordeeva-2014-v1',
    summary:'ШАМ оценивает семь самостоятельных типов академической мотивации студентов: три внутренних, три внешних и амотивацию. Методика содержит 28 утверждений — по четыре на каждую шкалу. Чем выше сумма, тем сильнее выражен соответствующий мотив.',
    steps:['Каждый ответ оценивается напрямую от 1 («совсем не соответствует») до 5 («вполне соответствует»); обратных пунктов нет.','Для каждой из семи шкал складываются ответы на четыре относящихся к ней пункта.','Результат каждой шкалы находится в диапазоне 4–20 баллов. Общий балл по всем 28 пунктам не рассчитывается.','Результат формируется только при наличии всех 28 ответов.'],
    keys:[{label:'Познавательная мотивация',value:'Пункты 1, 8, 15, 22.'},{label:'Мотивация достижения',value:'Пункты 2, 9, 16, 23.'},{label:'Мотивация саморазвития',value:'Пункты 3, 10, 17, 24.'},{label:'Мотивация самоуважения',value:'Пункты 4, 11, 18, 25.'},{label:'Интроецированная мотивация',value:'Пункты 5, 12, 19, 26.'},{label:'Экстернальная мотивация',value:'Пункты 6, 13, 20, 27.'},{label:'Амотивация',value:'Пункты 7, 14, 21, 28.'}],
    norms:[{label:'Диапазон каждой шкалы',value:'4–20 баллов. Более высокий балл означает большую выраженность соответствующего типа мотивации.'},{label:'Выборка разработки, N=459',value:'M (SD): познавательная — 16,16 (3,46); достижения — 14,33 (3,89); саморазвития — 15,76 (3,29); самоуважения — 15,08 (3,98); интроецированная — 12,69 (4,16); экстернальная — 11,07 (4,01); амотивация — 6,31 (3,19).'}],
    notes:['Авторы не предлагают универсальных диагностических порогов «низкий / средний / высокий». Результат следует рассматривать как профиль семи независимых мотивов.','Средние и стандартные отклонения выборки разработки приведены только как справочные описательные данные, а не как клинические нормы.','Методика разработана и валидизирована для студентов вузов; школьная версия ШАМ-Ш является отдельным инструментом и здесь не используется.'],
    sources:[{title:'Гордеева, Сычев, Осин — «Опросник „Шкалы академической мотивации“» (2014), полный текст и ключ',url:'https://istina.msu.ru/media/publications/article/de8/018/6933467/96-107_Gordeeva_final.pdf'},{title:'Карточка публикации НИУ ВШЭ',url:'https://publications.hse.ru/articles/118240237'},{title:'Копия статьи в репозитории НИУ ВШЭ',url:'https://publications.hse.ru/pubs/share/folder/y93jdtmioo/122549995.pdf'},{title:'Авторская копия публикации (Е. Н. Осин)',url:'https://www.researchgate.net/publication/287265976_Academic_motivation_scales_questionnaire'}]
  },
  test_8:{
    code:'test_8',title:'Academic Motivation Scale, AMS-C 28',version:'ams-c28-vallerand-v1',
    summary:'Официальная англоязычная College Version измеряет семь самостоятельных типов академической мотивации. Методика используется без перевода, чтобы не подменять валидированную версию непроверенной адаптацией.',
    steps:['Ответы задаются по шкале 1–7: от «Does not correspond at all» до «Corresponds exactly».','Обратных пунктов нет.','Для каждой шкалы рассчитывается среднее четырёх пунктов; диапазон результата 1–7.','Общий балл не рассчитывается. Результат формируется только при наличии всех 28 ответов.'],
    keys:[{label:'Intrinsic motivation — to know',value:'2, 9, 16, 23.'},{label:'Intrinsic motivation — toward accomplishment',value:'6, 13, 20, 27.'},{label:'Intrinsic motivation — to experience stimulation',value:'4, 11, 18, 25.'},{label:'Extrinsic motivation — identified',value:'3, 10, 17, 24.'},{label:'Extrinsic motivation — introjected',value:'7, 14, 21, 28.'},{label:'Extrinsic motivation — external regulation',value:'1, 8, 15, 22.'},{label:'Amotivation',value:'5, 12, 19, 26.'}],
    norms:[{label:'Диапазон каждой шкалы',value:'1,00–7,00. Более высокое значение означает большую выраженность соответствующего типа мотивации.'}],
    notes:['Универсальные диагностические пороги авторами не заданы: интерпретируется профиль семи шкал.','Версия предназначена только для исследовательских целей; при использовании требуется полная ссылка на первоисточник.','Пункты сохранены на английском языке. Валидированная русская адаптация этой конкретной версии не подменяется авторским переводом.'],
    sources:[{title:'Официальный бланк AMS-C 28 и авторский ключ',url:'https://lrcs.uqam.ca/wp-content/uploads/2017/08/emec_en.pdf'},{title:'Официальная страница шкал лаборатории авторов',url:'https://www.lrcs.uqam.ca/en/scales/'},{title:'Vallerand et al. — первичная публикация AMS (1992)',url:'https://doi.org/10.1177/0013164492052004025'},{title:'Авторская копия первичной публикации',url:'https://www.lrcs.uqam.ca/wp-content/uploads/2017/04/The-academic-motivation-scale.pdf'}]
  },
  test_9:{
    code:'test_9',title:'Шкала отчуждения от учебы',version:'study-alienation-osin-2015-v1',
    summary:'Краткая версия Е. Н. Осина измеряет четыре взаимосвязанные формы отчуждения от учебной деятельности у школьников и студентов. Чем выше средний балл, тем сильнее выражено соответствующее переживание отчуждения.',
    steps:['Используются 12 пунктов, оставшихся после исключения пунктов 1, 11, 14 и 16 исходной 16-пунктовой формы.','Все ответы учитываются напрямую по шкале 1–5; обратных пунктов нет.','Для каждой из четырёх субшкал рассчитывается среднее трёх пунктов.','Общий показатель — среднее всех 12 пунктов. Результат рассчитывается только при полном протоколе.'],
    keys:[{label:'Вегетативность',value:'Пункты 4, 8, 11.'},{label:'Бессилие',value:'Пункты 1, 5, 9.'},{label:'Нигилизм',value:'Пункты 2, 6, 12.'},{label:'Авантюризм',value:'Пункты 3, 7, 10.'},{label:'Общий показатель',value:'Среднее всех 12 пунктов; диапазон 1–5.'}],
    norms:[{label:'Студенты, N=395',value:'Общее отчуждение от учебы: M=2,40; SD=0,64.'},{label:'Старшеклассники, N=194',value:'Общее отчуждение от учебы: M=2,69; SD=0,65.'}],
    notes:['Средние двух выборок приведены только как справочные данные статьи и не являются универсальными диагностическими порогами.','Методика не устанавливает диагноз и не должна использоваться для индивидуальных санкций или решений об обучающемся.','Материал опубликован по лицензии CC BY-NC 4.0; эта реализация предназначена только для некоммерческого исследовательского использования.'],
    sources:[{title:'Осин — первичная публикация, полный бланк, сокращение и ключ (2015)',url:'https://doi.org/10.17759/pse.2015200406'},{title:'Полный текст на PsyJournals и лицензия CC BY-NC 4.0',url:'https://psyjournals.ru/journals/pse/archive/2015_n4/osin'},{title:'Независимое применение краткой версии и повторная публикация ключа (2020)',url:'https://doi.org/10.17759/pse.2020250202'},{title:'Условия лицензии CC BY-NC 4.0',url:'https://creativecommons.org/licenses/by-nc/4.0/'}]
  },
  test_10:{
    code:'test_10',title:'General Procrastination Scale, GPS — Student Form',version:'gps-lay-student-1986-v1',
    summary:'Original English 20-item student form measuring a general dispositional tendency to delay intended actions. Higher totals indicate stronger procrastination tendencies.',
    steps:['Responses are scored from 1 (Extremely Uncharacteristic) to 5 (Extremely Characteristic).','Items 3, 4, 6, 8, 11, 13, 14, 15, 18, and 20 are reverse-scored as 6 − response.','All 20 adjusted values are summed. The total ranges from 20 to 100; the displayed average ranges from 1 to 5.','A result is calculated only for a complete 20-item protocol.'],
    keys:[{label:'Direct items',value:'1, 2, 5, 7, 9, 10, 12, 16, 17, 19.'},{label:'Reverse-scored items',value:'3, 4, 6, 8, 11, 13, 14, 15, 18, 20. Formula: 6 − response.'},{label:'Total',value:'Sum of all 20 adjusted responses; range 20–100.'}],
    notes:['The authors do not provide universal diagnostic cutoffs. The platform therefore reports a continuous score without “low / medium / high” categories.','GPS is a research self-report scale and does not diagnose a disorder.','The original English student form is retained; it is not replaced by an unvalidated Russian translation.'],
    sources:[{title:'Lay — original GPS publication (1986)',url:'https://doi.org/10.1016/0092-6566(86)90127-3'},{title:'York University — 20-item questionnaire',url:'https://www.yorku.ca/rokada/psyctest/procrast.pdf'},{title:'Salford PsyTech — scoring and “No restrictions” usage statement',url:'https://hub.salford.ac.uk/psytech/equipment-resources/questionnaire-battery/procrastination-scale/'},{title:'PsyToolkit — independent student-form transcription and scoring',url:'https://www.psytoolkit.org/survey-library/procrastination-gp.html'}]
  },
  test_11:{
    code:'test_11',title:'Pure Procrastination Scale, PPS-12',version:'pps-steel-2010-v1',
    summary:'The original English PPS-12 measures a general procrastination tendency. All items point in the same direction: higher mean and total scores indicate more procrastination.',
    steps:['Responses are scored directly from 1 (“Very seldom or not true of me”) to 5 (“Very often true, or true with me”).','There are no reverse-scored items.','The primary PPS score is the mean of all 12 responses (range 1–5); the equivalent raw total ranges from 12 to 60.','For research transparency, the platform also reports means for the three item-origin groups identified in later validation work. A result is calculated only for a complete protocol.'],
    keys:[{label:'Decisional delay',value:'Items 1–3; mean of three responses.'},{label:'Implemental delay',value:'Items 4–8; mean of five responses.'},{label:'Lateness / timeliness',value:'Items 9–12; mean of four responses.'},{label:'Overall PPS',value:'Mean of all 12 direct responses; equivalent total 12–60.'}],
    notes:['Steel originally proposed a general one-factor score. Later cross-national research found that the three item-origin groups fit the data better; the profile is therefore shown alongside, not instead of, the overall score.','No universal diagnostic cutoffs are defined. The platform reports continuous research scores and does not label them “low”, “medium”, or “high”.','PPS-5, PPS-11, and translated adaptations are distinct versions and are not mixed with this original English PPS-12.','This self-report research measure does not establish a clinical diagnosis.'],
    sources:[{title:'Steel — original development of PPS (2010)',url:'https://doi.org/10.1016/j.paid.2010.02.025'},{title:'APA PsycTESTS record for PPS',url:'https://doi.org/10.1037/t10499-000'},{title:'Steel & Svartdal — full item text, response anchors, validation, CC BY (2017)',url:'https://doi.org/10.3389/fpsyg.2017.01927'},{title:'Svartdal et al. — six-country validation and mean scoring (2016)',url:'https://doi.org/10.3389/fpsyg.2016.01307'}]
  },
  test_12:{
    code:'test_12',title:'Big Five Inventory–2, BFI-2 — русская версия',version:'bfi2-ru-shchebetenko-2018-v1',
    summary:'Официальная русская 60-пунктовая версия BFI-2 оценивает пять широких областей личности и по три более узких аспекта внутри каждой. Результаты являются непрерывным профилем, а не типами личности или диагнозами.',
    steps:['Ответы задаются по шкале 1–5 от «Совершенно не согласен» до «Совершенно согласен».','Для реверсивного пункта применяется формула 6 − ответ; полный официальный ключ используется отдельно для каждой области и аспекта.','Показатель каждой из пяти областей — среднее 12 скорректированных пунктов; показатель каждого из 15 аспектов — среднее четырёх пунктов. Все результаты находятся в диапазоне 1–5.','Платформа рассчитывает профиль только после ответа на все 60 пунктов и не создаёт неподтверждённые категории или процентили.'],
    keys:[{label:'Экстраверсия',value:'1, 6, 11R, 16R, 21, 26R, 31R, 36R, 41, 46, 51R, 56.'},{label:'Доброжелательность',value:'2, 7, 12R, 17R, 22R, 27, 32, 37R, 42R, 47R, 52, 57.'},{label:'Добросовестность',value:'3R, 8R, 13, 18, 23R, 28R, 33, 38, 43, 48R, 53, 58R.'},{label:'Негативная эмоциональность',value:'4R, 9R, 14, 19, 24R, 29R, 34, 39, 44R, 49R, 54, 59.'},{label:'Открытость опыту',value:'5R, 10, 15, 20, 25R, 30R, 35, 40, 45R, 50R, 55R, 60.'},{label:'Аспекты',value:'15 аспектов рассчитываются по официальным четырёхпунктовым ключам, опубликованным на второй странице русского бланка.'}],
    notes:['Авторы не публикуют официальных универсальных норм BFI-2. Поэтому платформа показывает исходные средние 1–5 без категорий «низкий / средний / высокий» и без самодельных процентилей.','Ни одна черта сама по себе не является хорошей или плохой. Профиль не устанавливает психиатрический диагноз и не должен использоваться как единственное основание для кадровых, учебных или клинических решений.','BFI-2 защищён авторским правом, но правообладатели прямо разрешают бесплатное использование исследователям для некоммерческих исследований. Коммерческое использование требует отдельного разрешения.','Использована официально размещённая авторами русская версия; она не заменена самостоятельным переводом.'],
    sources:[{title:'Berkeley Personality Lab — условия использования, формы и scoring BFI-2',url:'https://www.ocf.berkeley.edu/~johnlab/bfi.html'},{title:'Официальный русский бланк и полный ключ BFI-2',url:'https://www.colby.edu/wp-content/uploads/2018/08/bfi2-form-russian.pdf'},{title:'Soto & John — разработка BFI-2 (2017)',url:'https://doi.org/10.1037/pspp0000096'},{title:'Shchebetenko et al. — психометрическая проверка русской версии (2020)',url:'https://doi.org/10.1177/1073191119860901'}]
  },
  test_13:{
    code:'test_13',title:'Краткая версия Big Five Inventory–2, BFI-2-S — русская версия',version:'bfi2-s-ru-mishkevich-2022-v1',
    summary:'Официально опубликованная русская 30-пунктовая форма BFI-2-S оценивает пять широких областей личности и 15 двухпунктовых аспектов. Это самостоятельная короткая версия, а не произвольное сокращение полного BFI-2.',
    steps:['Ответы задаются по шкале 1–5 от «Совершенно не согласен» до «Совершенно согласен».','Реверсивные ответы преобразуются по формуле 6 − ответ в точном соответствии с опубликованным ключом.','Показатель каждой области — среднее шести скорректированных пунктов; показатель каждого аспекта — среднее двух пунктов. Диапазон всех средних — 1–5.','Расчёт выполняется только для полного протокола из 30 ответов.'],
    keys:[{label:'Экстраверсия',value:'1R, 6, 11, 16, 21R, 26R.'},{label:'Доброжелательность',value:'2, 7R, 12, 17R, 22, 27R.'},{label:'Добросовестность',value:'3R, 8R, 13, 18, 23, 28R.'},{label:'Негативная эмоциональность',value:'4, 9, 14R, 19R, 24R, 29.'},{label:'Открытость опыту',value:'5, 10R, 15, 20R, 25, 30R.'},{label:'Аспекты',value:'15 аспектов рассчитываются по опубликованным двухпунктовым ключам приложения к русской апробации.'}],
    notes:['В статье прямо отмечено, что некоторые двухпунктовые аспекты имеют ограниченную внутреннюю согласованность; аспектные результаты следует интерпретировать осторожнее, чем области.','Платформа не назначает неподтверждённые категории, нормы или процентили: выводятся непрерывные средние 1–5.','Профиль не является диагнозом и не должен служить единственным основанием для решений с высокими последствиями.','BFI-2 защищён авторским правом; правообладатели разрешают бесплатное применение исследователями в некоммерческих исследованиях. Для коммерческого использования необходимо отдельное разрешение.'],
    sources:[{title:'Мишкевич и соавт. — русская апробация, полный бланк и ключ BFI-2-S (2022)',url:'https://www.colby.edu/wp-content/uploads/2022/03/Miskevich_et_al_2022.pdf'},{title:'Berkeley Personality Lab — формы BFI-2 и условия использования',url:'https://www.ocf.berkeley.edu/~johnlab/bfi.html'},{title:'Soto & John — разработка BFI-2-S и BFI-2-XS (2017)',url:'https://doi.org/10.1016/j.jrp.2017.02.004'},{title:'Soto & John — исходная иерархическая модель BFI-2 (2017)',url:'https://doi.org/10.1037/pspp0000096'}]
  },
  test_14:{
    code:'test_14',title:'Краткий пятифакторный опросник личности, TIPI-RU',version:'tipi-ru-sergeeva-2016-v1',
    summary:'TIPI-RU — валидированная русская адаптация десятипунктового TIPI. Она даёт краткий исследовательский профиль пяти областей личности, используя по два пункта на область.',
    steps:['Каждый пункт оценивается по шкале 1–7: от полного несогласия до полного согласия; 4 означает «нечто среднее».','Пункты 2, 4, 6, 8 и 10 кодируются обратно по формуле 8 − ответ.','Каждая область рассчитывается как среднее двух пунктов по опубликованному ключу и находится в диапазоне 1–7.','Расчёт выполняется только после ответа на все 10 пунктов.'],
    keys:[{label:'Экстравертность',value:'1 и 6R.'},{label:'Дружелюбие',value:'2R и 7.'},{label:'Добросовестность',value:'3 и 8R.'},{label:'Эмоциональная стабильность',value:'4R и 9.'},{label:'Открытость новому опыту',value:'5 и 10R.'}],
    notes:['TIPI-RU предназначен для ситуаций, где важна предельная краткость. Двухпунктовые шкалы не заменяют более подробный личностный опросник, когда требуется детальный профиль.','Авторы русской адаптации рекомендуют TIPI-RU для неклинических условий, в том числе интернет-опросов; методика не является клинической диагностикой.','Не используются самодельные категории «низкий / средний / высокий», универсальные нормы или процентили: платформа показывает исходные средние 1–7.','Это версия TIPI-RU Сергеевой, Кириллова и Джумагуловой, а не отдельная русская адаптация КОБТ Корниловой и Чумаковой.'],
    sources:[{title:'Сергеева, Кириллов, Джумагулова — полный текст, бланк и ключ TIPI-RU (2016)',url:'https://doi.org/10.17759/exppsy.2016090311'},{title:'Копия русской статьи и формы в Gosling Personality Lab',url:'https://gosling.psy.utexas.edu/wp-content/uploads/2022/07/TIPI-Russian2016.pdf'},{title:'Gosling Personality Lab — разрешение исследователям свободно использовать шкалы',url:'https://gosling.psy.utexas.edu/scales-weve-developed/'},{title:'Gosling, Rentfrow, Swann — оригинальная разработка TIPI (2003)',url:'https://doi.org/10.1016/S0092-6566(03)00046-1'}]
  },
  test_15:{
    code:'test_15',title:'IPIP-NEO-120 — public-domain five-factor inventory',version:'ipip-neo-120-johnson-2014-v1',
    summary:'IPIP-NEO-120 is a 120-item public-domain inventory developed by John A. Johnson from the International Personality Item Pool. It estimates the five broad domains and 30 facets related to the NEO PI-R model, but it is not the commercial NEO PI-R or NEO-PI-3.',
    steps:['Responses use the official IPIP 1–5 accuracy scale from Very inaccurate to Very accurate.','For + keyed items, responses are scored directly from 1 to 5. For - keyed items, responses are reverse-scored as 6 − response.','Each of the 30 facets is the sum and mean of four keyed items. Each broad domain is the sum and mean of its 24 keyed items.','A result is calculated only for a complete 120-item protocol.'],
    keys:[{label:'Domains',value:'Neuroticism, Extraversion, Openness to Experience, Agreeableness, Conscientiousness; 24 items each.'},{label:'Facets',value:'30 facets: N1–N6, E1–E6, O1–O6, A1–A6, C1–C6; four items each, exactly as listed in Johnson (2014), Table 1.'},{label:'Reverse scoring',value:'All items marked with a minus sign in Johnson (2014), Table 1 are scored as 6 − response.'}],
    notes:['The platform uses the original English item text. No unofficial Russian translation is substituted for the validated source wording.','The IPIP materials are public domain, but IPIP-NEO-120 should not be represented as NEO PI-R or NEO-PI-3. It is a public-domain representation targeting similar constructs.','The platform reports continuous raw means from 1 to 5 and does not create unvalidated Russian norms, percentiles, or diagnostic categories.','Johnson notes that the 4-item facet scales are suitable for research use, but should not be used for important individual decisions.'],
    sources:[{title:'Official IPIP website — public-domain item pool',url:'https://ipip.ori.org/'},{title:'Official IPIP permission statement',url:'https://ipip.ori.org/newPermission.htm'},{title:'Official IPIP scoring instructions',url:'https://ipip.ori.org/newScoringInstructions.htm'},{title:'Johnson — development and validation of the IPIP-NEO-120 (2014)',url:'https://bpb-us-e1.wpmucdn.com/sites.psu.edu/dist/1/163537/files/2023/07/IPIPNEO120.pdf'},{title:'Johnson article DOI',url:'https://doi.org/10.1016/j.jrp.2014.05.003'}]
  },
  test_16:{
    code:'test_16',title:'Mini-IPIP — 20-item public-domain Big Five inventory',version:'mini-ipip-donnellan-2006-v1',
    summary:'Mini-IPIP is a 20-item public-domain short form developed by Donnellan, Oswald, Baird, and Lucas (2006) from IPIP Big Five markers. It reports five broad personality scales, four items each.',
    steps:['Responses use the IPIP 1–5 accuracy scale from Very inaccurate to Very accurate.','Direct items are scored 1–5. Reverse-scored items are transformed as 6 − response.','Each Big Five scale is the sum and mean of four keyed items.','A result is calculated only for a complete 20-item protocol.'],
    keys:[{label:'Extraversion',value:'1, 6R, 11, 16R.'},{label:'Agreeableness',value:'2, 7R, 12, 17R.'},{label:'Conscientiousness',value:'3, 8R, 13, 18R.'},{label:'Neuroticism',value:'4, 9R, 14, 19R.'},{label:'Intellect / Imagination',value:'5, 10R, 15R, 20R.'}],
    notes:['The platform uses the original English item order from the article Appendix and the official IPIP scoring key.','The official IPIP key notes that Mini-IPIP is based on the 50-item IPIP lexical Big-Five markers and that Neuroticism is scored as the reverse of the lexical Emotional Stability scale.','Scores are continuous means from 1 to 5. No unvalidated norms, percentiles, or diagnostic categories are added.','Mini-IPIP is useful when brevity is important, but four-item broad scales should not be used as the sole basis for important individual decisions.'],
    sources:[{title:'Official IPIP Mini-IPIP scoring key',url:'https://www.ipip.ori.org/MiniIPIPKey.htm'},{title:'Official IPIP permission statement',url:'https://ipip.ori.org/newPermission.htm'},{title:'Official IPIP scoring instructions',url:'https://ipip.ori.org/newScoringInstructions.htm'},{title:'Donnellan et al. — Mini-IPIP validation article and Appendix (2006)',url:'https://faracivisiting.wordpress.com/wp-content/uploads/2010/04/donnellan-et-al-2006.pdf'},{title:'PubMed record and DOI',url:'https://pubmed.ncbi.nlm.nih.gov/16768595/'}]
  },
  test_17:{
    code:'test_17',title:'Шкала самооценки Розенберга, RSES',version:'rses-ru-zolotareva-2020-v1',
    summary:'RSES is a 10-item public-domain measure of global self-esteem. The platform uses the 0–30 scoring approach with reverse scoring for negatively worded items.',
    steps:['Каждый пункт оценивается от 0 до 3.','Прямые пункты: 1, 3, 4, 7, 10. Обратные пункты: 2, 5, 6, 8, 9.','Для обратных пунктов применяется преобразование 3 − ответ.','Итоговая сумма находится в диапазоне 0–30: чем выше балл, тем выше глобальная самооценка.'],
    keys:[{label:'Прямые пункты',value:'1, 3, 4, 7, 10.'},{label:'Обратные пункты',value:'2, 5, 6, 8, 9.'},{label:'Диапазон',value:'0–30 баллов.'}],
    notes:['RSES находится в public domain по странице University of Maryland.','Ориентир ниже 15 часто трактуется как возможная проблемно низкая самооценка, но платформа не выдаёт медицинский диагноз.','Для русской версии использован опубликованный ключ Золотарёвой: прямое и обратное кодирование 0–3.'],
    sources:[{title:'University of Maryland — public-domain permission and scoring',url:'https://socy.umd.edu/about-us/using-rosenberg-self-esteem-scale'},{title:'APA Measures Package — RSES scoring summary',url:'https://www.apa.org/obesity-guideline/rosenberg-self-esteem.pdf'},{title:'Золотарёва — валидность и надежность русскоязычной версии RSES',url:'https://publications.hse.ru/pubs/share/direct/383400468.pdf'}]
  }
};
