import{describe,expect,it}from'vitest';
import{tipiRuInstrument}from'../data/tipiRu.js';
import{scoreTipiRu,TIPI_RU_REVERSE_ITEMS}from'./tipiRu.js';
const answers=(value:number)=>new Map(Array.from({length:10},(_,index)=>[index+1,value]));
describe('scoreTipiRu',()=>{
  it('ships the published ten Russian items without inventing intermediate anchors',()=>{expect(tipiRuInstrument.questions).toHaveLength(10);expect(tipiRuInstrument.questions.map(q=>q.code)).toEqual(Array.from({length:10},(_,i)=>`test_14_${i+1}`));expect(tipiRuInstrument.questions.every(q=>q.options?.map(o=>o.value).join(',')==='1,2,3,4,5,6,7')).toBe(true);expect(tipiRuInstrument.questions[0].options?.map(o=>o.label)).toEqual(['1 — полное несогласие','2','3','4 — нечто среднее','5','6','7 — полное согласие'])});
  it('contains the complete published reverse key',()=>expect(TIPI_RU_REVERSE_ITEMS).toEqual([2,4,6,8,10]));
  it('checks the direction of every item through the actual scorer',()=>{const reverse=new Set<number>(TIPI_RU_REVERSE_ITEMS);const baseline=scoreTipiRu(answers(4))!;const baselineTotal=Object.values(baseline.scales).reduce((sum,x)=>sum+x.score,0);for(let item=1;item<=10;item++){const input=answers(4);input.set(item,5);const total=Object.values(scoreTipiRu(input)!.scales).reduce((sum,x)=>sum+x.score,0);expect(total-baselineTotal,`item ${item}`).toBe(reverse.has(item)?-1:1)}});
  it('calculates theoretical minima, neutral values, and maxima',()=>{const min=answers(1);TIPI_RU_REVERSE_ITEMS.forEach(i=>min.set(i,7));expect(Object.values(scoreTipiRu(min)!.scales).every(x=>x.average===1)).toBe(true);expect(Object.values(scoreTipiRu(answers(4))!.scales).every(x=>x.average===4)).toBe(true);const max=answers(7);TIPI_RU_REVERSE_ITEMS.forEach(i=>max.set(i,1));expect(Object.values(scoreTipiRu(max)!.scales).every(x=>x.average===7)).toBe(true)});
  it('matches a hand-calculated mixed protocol',()=>{const input=new Map([[1,7],[2,6],[3,5],[4,4],[5,3],[6,2],[7,1],[8,7],[9,6],[10,5]]);const result=scoreTipiRu(input)!;expect(result.scales.extraversion).toMatchObject({score:13,average:6.5});expect(result.scales.agreeableness).toMatchObject({score:3,average:1.5});expect(result.scales.conscientiousness).toMatchObject({score:6,average:3});expect(result.scales.emotionalStability).toMatchObject({score:10,average:5});expect(result.scales.openness).toMatchObject({score:6,average:3})});
  it('rejects incomplete, invalid, fractional, and wrong-key protocols',()=>{const incomplete=answers(4);incomplete.delete(10);expect(scoreTipiRu(incomplete)).toBeNull();const invalid=answers(4);invalid.set(10,8);expect(scoreTipiRu(invalid)).toBeNull();const fractional=answers(4);fractional.set(10,4.5);expect(scoreTipiRu(fractional)).toBeNull();const wrong=answers(4);wrong.delete(1);wrong.set(11,4);expect(scoreTipiRu(wrong)).toBeNull()});
});
